-- =========================================================
-- Database resep masakan Halal & Thoyyib (KIBAR UK, 2023)
-- Auto-generated dari resep_halal_thoyyib.json
-- Kompatibel MySQL / MariaDB
-- =========================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `langkah`;
DROP TABLE IF EXISTS `bahan`;
DROP TABLE IF EXISTS `resep_catatan`;
DROP TABLE IF EXISTS `resep`;

CREATE TABLE `resep` (
  `id` INT UNSIGNED NOT NULL,
  `nama` VARCHAR(150) NOT NULL,
  `kategori` VARCHAR(50) NOT NULL,
  `kontributor` VARCHAR(150) DEFAULT NULL,
  `kota` VARCHAR(100) DEFAULT NULL,
  `halaman` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `bahan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `resep_id` INT UNSIGNED NOT NULL,
  `grup` VARCHAR(150) NOT NULL COMMENT 'nama kelompok bahan, misal: Bahan, Bumbu Halus, Bahan A - dst',
  `urutan` INT UNSIGNED NOT NULL,
  `teks` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_bahan_resep` (`resep_id`),
  CONSTRAINT `fk_bahan_resep` FOREIGN KEY (`resep_id`) REFERENCES `resep` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `langkah` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `resep_id` INT UNSIGNED NOT NULL,
  `grup` VARCHAR(150) NOT NULL COMMENT 'nama sub-resep/tahap, misal: Cara Memasak, Sambal Krecek - Cara Memasak',
  `urutan` INT UNSIGNED NOT NULL,
  `instruksi` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_langkah_resep` (`resep_id`),
  CONSTRAINT `fk_langkah_resep` FOREIGN KEY (`resep_id`) REFERENCES `resep` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `resep_catatan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `resep_id` INT UNSIGNED NOT NULL,
  `jenis` VARCHAR(50) NOT NULL COMMENT 'tips, catatan, cara_penyajian, cara_penyimpanan, dsb',
  `teks` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_catatan_resep` (`resep_id`),
  CONSTRAINT `fk_catatan_resep` FOREIGN KEY (`resep_id`) REFERENCES `resep` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------
-- Data: resep
-- ---------------------------------------------------------
INSERT INTO `resep` (`id`, `nama`, `kategori`, `kontributor`, `kota`, `halaman`) VALUES
(1, 'Ayam Bakar Taliwang', 'Aneka Lauk dan Sayur', 'Rizkiyati Amalis Zhuraida', 'Southampton', '1'),
(2, 'Bakso Daging Sapi dengan Kuah Kaldu Tulang', 'Aneka Lauk dan Sayur', 'Lutfi Nia Kholida', 'Manchester', '2-3'),
(3, 'Gulai Udang Tahu Petai (Gudang Tape) ala Iza', 'Aneka Lauk dan Sayur', 'Desmaliza', 'Manchester', '4'),
(4, 'Ayam Glabed', 'Aneka Lauk dan Sayur', 'Nadiah Afif', 'Nottingham', '5'),
(5, 'Resep Sambal Tuna', 'Aneka Lauk dan Sayur', 'Rini Rezeki', 'Manchester', '7'),
(6, 'Mie Aceh Udang', 'Aneka Lauk dan Sayur', 'Rinal Sahputra', 'Manchester', '8-9'),
(7, 'Seafood Saus Padang Bintang Toedjoeh', 'Aneka Lauk dan Sayur', 'Ririn Nurwulan', 'Manchester', '10'),
(8, 'Spaghetti Dendeng Balado', 'Aneka Lauk dan Sayur', 'Anggi Anggraeni', 'Manchester', '11'),
(9, 'Sambel Goreng Hati Kentang', 'Aneka Lauk dan Sayur', 'Yuni Ira Nurdiana', 'Leeds', '12'),
(10, 'Ungkep Ayam/Daging/Hati Ayam', 'Aneka Lauk dan Sayur', 'Yuni Ira Nurdiana', 'Leeds', '13'),
(11, 'Gudeg Jogja Komplet', 'Aneka Lauk dan Sayur', 'Sasa (Wiwara Awisarita)', 'Birmingham', '14-16'),
(12, 'Ikan Goreng Dabu-Dabu for Kids', 'Aneka Lauk dan Sayur', 'Irsalina Dwiyanti', 'Glasgow', '17'),
(13, 'Ayam Bakar Solo', 'Aneka Lauk dan Sayur', 'Bety Navitasari', 'Nottingham', '18'),
(14, 'Rolade', 'Aneka Lauk dan Sayur', 'Dyah Puspita', 'Nottingham', '19'),
(15, 'Iga Bakar', 'Aneka Lauk dan Sayur', 'Bety Navitasari', 'Nottingham', '20'),
(16, 'Kambing Masak Tomat', 'Aneka Lauk dan Sayur', 'Dewi SO', 'Swindon', '20'),
(17, 'Perkedel Ikan Tuna ala Dina', 'Aneka Lauk dan Sayur', 'Dina', 'Huddersfield', '21'),
(18, 'Bothok Tempe', 'Aneka Lauk dan Sayur', 'Bety Navitasari', 'Nottingham', '22'),
(19, 'Brambang Asem', 'Aneka Lauk dan Sayur', 'Tuti Nurmuntaha', 'Newcastle', '23'),
(20, 'Cah Mustard Green (Kai Choi)', 'Aneka Lauk dan Sayur', 'Naniek Muchdi', 'London', '24'),
(21, 'Sup Ayam Bungkus Telor', 'Aneka Lauk dan Sayur', 'Tuti Nurmuntaha', 'Newcastle', '25'),
(22, 'Sup Iga Kambing', 'Aneka Lauk dan Sayur', 'Bety Navitasari', 'Nottingham', '26'),
(23, 'Soto Banjar', 'Aneka Lauk dan Sayur', 'Qurrotin A''yunina Afianti', 'Sheffield', '27'),
(24, 'Ikan Bakar Manis', 'Aneka Lauk dan Sayur', 'Endah Sulistyowati', 'Nottingham', '28'),
(25, 'Cap Cay', 'Aneka Lauk dan Sayur', 'Endah Sulistyowati', 'Nottingham', '29'),
(26, 'Ceker Mercon', 'Aneka Lauk dan Sayur', 'Endah Sulistyowati', 'Nottingham', '30'),
(27, 'Telur Ceplok Kuah Santan', 'Aneka Lauk dan Sayur', 'Endah Sulistyowati', 'Nottingham', '31'),
(28, 'Telur Dadar Padang', 'Aneka Lauk dan Sayur', 'Endah Sulistyowati', 'Nottingham', '32'),
(29, 'Oseng Pare Teri', 'Aneka Lauk dan Sayur', 'Endah Sulistyowati', 'Nottingham', '33'),
(30, 'Spaghetti Goreng Jawa', 'Aneka Lauk dan Sayur', 'Endah Sulistyowati', 'Nottingham', '34'),
(31, 'Mie Ayam Ceker', 'Aneka Lauk dan Sayur', 'Endah Sulistyowati', 'Nottingham', '35'),
(32, 'Kue Cantik Manis', 'Kudapan/Snack', 'Fitri Pratiwi Rasyid', 'Nottingham', '37-38'),
(33, 'Es Teler Nottingham', 'Kudapan/Snack', 'Bety Navitasari', 'Nottingham', '39'),
(34, 'Setup Buah', 'Kudapan/Snack', 'Endah Sulistyowati', 'Nottingham', '40'),
(35, 'Pisang Selimut', 'Kudapan/Snack', 'Endah Sulistyowati', 'Nottingham', '41'),
(36, 'Tahu Gejrot Khas Cirebon', 'Kudapan/Snack', 'Irsalina Dwiyanti', 'Glasgow', '42'),
(37, 'Basque Burnt Cheesecake', 'Kudapan/Snack', 'Andhika Prima Prasetyo', 'Salford', '43'),
(38, 'Keik Pisang Cokelat', 'Kudapan/Snack', 'Sefrina Widyanti', 'Dundee, Scotland', '44'),
(39, 'Kartika Sari Notts', 'Kudapan/Snack', 'Melyza Perdana', 'Nottingham', '45'),
(40, 'Boh Rom-rom Ubi Manis', 'Kudapan/Snack', 'Rahma Po', NULL, '46'),
(41, 'Dadar Gulung Ayu', 'Kudapan/Snack', 'Bety Navitasari', 'Nottingham', '47'),
(42, 'Wingko', 'Kudapan/Snack', 'Bety Navitasari', 'Nottingham', '48'),
(43, 'Sosis Solo', 'Kudapan/Snack', 'Bety Navitasari', 'Nottingham', '49'),
(44, 'Kroket Kentang', 'Kudapan/Snack', 'Bety Navitasari', 'Nottingham', '50'),
(45, 'Kue Lumpur', 'Kudapan/Snack', 'Asri Mitchell', 'Nottingham', '51'),
(46, 'Pulut Sri Muka', 'Kudapan/Snack', 'Bety Navitasari', 'Nottingham', '52'),
(47, 'Sari Rasa Ketan Coklat', 'Kudapan/Snack', 'Etty', 'Burton on Trent', '53'),
(48, 'Gethuk', 'Kudapan/Snack', 'Endah Sulistyowati', 'Nottingham', '54'),
(49, 'Ketan Unti', 'Kudapan/Snack', 'Endah Sulistyowati', 'Nottingham', '55'),
(50, 'Klepon', 'Kudapan/Snack', 'Endah Sulistyowati', 'Nottingham', '56'),
(51, 'Martabak Daging', 'Kudapan/Snack', 'Endah Sulistyowati', 'Nottingham', '57'),
(52, 'Rujak Serut', 'Kudapan/Snack', 'Bety Navitasari', 'Nottingham', '58');

-- ---------------------------------------------------------
-- Data: bahan
-- ---------------------------------------------------------
INSERT INTO `bahan` (`resep_id`, `grup`, `urutan`, `teks`) VALUES
(1, 'bahan', 1, '1 kg ayam, potong-potong sesuai selera'),
(1, 'bahan', 2, '2 sdm air jeruk nipis'),
(1, 'bahan', 3, '1 sdt garam'),
(1, 'bahan', 4, '300 ml santan encer'),
(1, 'bahan', 5, 'Minyak untuk menumis'),
(1, 'bumbu halus', 1, '10 bawang merah'),
(1, 'bumbu halus', 2, '7 bawang putih'),
(1, 'bumbu halus', 3, '1 cabe merah besar'),
(1, 'bumbu halus', 4, '3 kemiri'),
(1, 'bumbu halus', 5, '1.5 sdt terasi'),
(1, 'bumbu halus', 6, '1 sdt gula merah'),
(1, 'bumbu halus', 7, '1 sdt garam'),
(2, 'bahan bakso', 1, '1/2 kg daging sapi (jangan pakai minced beef untuk mendapatkan tekstur yang bagus)'),
(2, 'bahan bakso', 2, '50 gr tepung tapioka'),
(2, 'bahan bakso', 3, '10 butir bawang putih'),
(2, 'bahan bakso', 4, '1 scallion/shallot besar'),
(2, 'bahan bakso', 5, '1/2 sendok teh baking powder'),
(2, 'bahan bakso', 6, '2 butir telur (ambil putih telurnya saja)'),
(2, 'bahan bakso', 7, '1/2 sendok teh pala'),
(2, 'bahan bakso', 8, '1 sendok teh bubuk merica putih'),
(2, 'bahan bakso', 9, '1 sendok makan kaldu jamur/kaldu lainnya'),
(2, 'bahan bakso', 10, '1/2 sendok teh garam'),
(2, 'bahan bakso', 11, 'Es batu'),
(2, 'bahan bakso', 12, 'Air'),
(2, 'bahan kuah kaldu tulang', 1, '1 kg tulang sapi bagian kaki atau rib'),
(2, 'bahan kuah kaldu tulang', 2, '3 L air'),
(2, 'bahan kuah kaldu tulang', 3, '7 butir bawang putih'),
(2, 'bahan kuah kaldu tulang', 4, '1/2 scallion/shallot besar'),
(2, 'bahan kuah kaldu tulang', 5, '1/2 sendok teh pala'),
(2, 'bahan kuah kaldu tulang', 6, '1 sendok teh bubuk merica putih'),
(2, 'bahan kuah kaldu tulang', 7, 'Kaldu jamur/kaldu lainnya secukupnya'),
(2, 'bahan kuah kaldu tulang', 8, 'Garam secukupnya'),
(2, 'bahan kuah kaldu tulang', 9, 'Daun bawang'),
(2, 'bahan sambal bawang', 1, '15 butir cabe rawit bird eye chilli'),
(2, 'bahan sambal bawang', 2, '7 butir bawang putih'),
(2, 'bahan sambal bawang', 3, 'Sedikit garam dan gula putih'),
(2, 'pelengkap', 1, 'Mie kuning/bihun'),
(2, 'pelengkap', 2, 'Tahu goreng'),
(2, 'pelengkap', 3, 'Daun bawang'),
(2, 'pelengkap', 4, 'Bawang goreng'),
(2, 'pelengkap', 5, 'Pangsit'),
(3, 'bahan', 1, '250 gram udang tanpa kepala, cuci bersih dan dilumurkan air jeruk nipis dan garam'),
(3, 'bahan', 2, '2 buah tahu putih dipotong kotak-kotak sedang'),
(3, 'bahan', 3, '2 buah kentang ukuran sedang dipotong kotak-kotak sedang'),
(3, 'bahan', 4, '10 biji petai atau sesukanya'),
(3, 'bumbu halus', 1, '5 buah cabai merah besar'),
(3, 'bumbu halus', 2, '3-6 siung bawang merah/shallot tergantung ukuran'),
(3, 'bumbu halus', 3, '3 siung bawang putih'),
(3, 'bumbu halus', 4, '1 ruas lengkuas'),
(3, 'bumbu halus', 5, '1 ruas jahe'),
(3, 'bumbu halus', 6, '1 ruas kunyit / 1 sdt bubuk kunyit'),
(3, 'bumbu halus', 7, '3 butir kemiri (optional)'),
(3, 'bahan lain', 1, '4 sdm santan bubuk'),
(3, 'bahan lain', 2, '1 batang serai, memarkan'),
(3, 'bahan lain', 3, '3 lembar daun jeruk purut'),
(3, 'bahan lain', 4, '3 lembar daun salam'),
(3, 'bahan lain', 5, 'Air secukupnya'),
(3, 'bahan lain', 6, 'Garam secukupnya'),
(3, 'bahan lain', 7, 'Penyedap rasa secukupnya'),
(3, 'bahan lain', 8, 'Minyak goreng untuk menumis bumbu'),
(4, 'bahan', 1, '1 ekor ayam dipotong kecil-kecil'),
(4, 'bahan', 2, '1/2 potong jeruk nipis, ambil airnya'),
(4, 'bahan', 3, '1L santan encer'),
(4, 'bahan', 4, '300ml santan kental'),
(4, 'bahan', 5, '100ml susu (whole milk)'),
(4, 'bahan', 6, '4 lembar daun jeruk, buang tulangnya dan sobek-sobek'),
(4, 'bahan', 7, '1 buah tomat, cincang halus'),
(4, 'bumbu kuah dihaluskan', 1, '1 bawang bombay'),
(4, 'bumbu kuah dihaluskan', 2, '6 siung bawang putih'),
(4, 'bumbu kuah dihaluskan', 3, '1 sdm ketumbar'),
(4, 'bumbu kuah dihaluskan', 4, '1/2 sdt jinten'),
(4, 'bumbu kuah dihaluskan', 5, '1 sdt lada'),
(4, 'bumbu kuah dihaluskan', 6, '3 cm kunyit'),
(4, 'bumbu kuah dihaluskan', 7, '2 cm jahe'),
(4, 'bumbu kuah dihaluskan', 8, '5 cm sereh bagian putih'),
(4, 'bumbu kuah dihaluskan', 9, 'Garam secukupnya'),
(4, 'bumbu ayam', 1, '6 siung bawang putih'),
(4, 'bumbu ayam', 2, '1 cm kunyit'),
(4, 'bumbu ayam', 3, '1 sdt ketumbar'),
(4, 'bumbu ayam', 4, '1/2 sdt lada'),
(4, 'bumbu ayam', 5, '200ml santan encer/air'),
(4, 'bumbu ayam', 6, 'Secukupnya garam'),
(4, 'pelengkap', 1, 'Lontong/ketupat'),
(4, 'pelengkap', 2, 'Bawang goreng'),
(4, 'pelengkap', 3, 'Telur rebus'),
(4, 'pelengkap', 4, 'Jeruk nipis'),
(4, 'pelengkap', 5, 'Sambal cabai rawit'),
(4, 'pelengkap', 6, '200 gr tempe/tahu putih potong kotak 2cm, goreng sebentar'),
(5, 'bahan', 1, '1 kaleng tuna ukuran 150 gr'),
(5, 'bahan', 2, '150 gr bawang merah atau shallots'),
(5, 'bahan', 3, '150 gr cabe merah besar'),
(5, 'bahan', 4, '15 gr cabe rawit'),
(5, 'bahan', 5, '10 gr sereh'),
(5, 'bahan', 6, '50 ml air'),
(5, 'bahan', 7, '5 gr gula merah'),
(5, 'bahan', 8, '1/2 sdt garam'),
(5, 'bahan', 9, '8 sdm minyak goreng'),
(6, 'bumbu halus', 1, '100 g bawang merah'),
(6, 'bumbu halus', 2, '30 g bawang putih'),
(6, 'bumbu halus', 3, '2 buah tomat ukuran sedang'),
(6, 'bumbu halus', 4, 'Cabe rawit secukupnya (boleh tidak digunakan jika tidak suka pedas)'),
(6, 'bumbu halus', 5, '3 sendok makan paprika bubuk'),
(6, 'bumbu halus', 6, '1 sendok teh jahe bubuk'),
(6, 'bahan bahan lain', 1, '500 g mie kuning (rebus sekitar 4 menit dan tiriskan)'),
(6, 'bahan bahan lain', 2, 'Udang secukupnya'),
(6, 'bahan bahan lain', 3, '50 g tauge'),
(6, 'bahan bahan lain', 4, '1 sendok teh jinten hitam bubuk'),
(6, 'bahan bahan lain', 5, '1 sendok teh bumbu kari'),
(6, 'bahan bahan lain', 6, 'Daun bawang secukupnya (diiris tipis)'),
(6, 'bahan bahan lain', 7, 'Daun seledri secukupnya (diiris tipis)'),
(6, 'bahan bahan lain', 8, 'Kecap asin dan kecap manis secukupnya'),
(6, 'bahan bahan lain', 9, '1 sendok makan minyak wijen'),
(6, 'bahan bahan lain', 10, '1 sendok makan cuka'),
(6, 'bahan bahan lain', 11, 'Kacang tanah goreng (untuk pelengkap)'),
(6, 'bahan bahan lain', 12, '1 butir telur (digoreng mata sapi sebagai pelengkap)'),
(6, 'bahan bahan lain', 13, 'Bawang goreng secukupnya'),
(6, 'bahan bahan lain', 14, 'Kerupuk udang secukupnya'),
(6, 'bahan bahan lain', 15, 'Irisan tomat secukupnya'),
(6, 'bahan bahan lain', 16, '1/4 cup air'),
(6, 'bahan bahan lain', 17, 'Garam secukupnya'),
(6, 'bahan bahan lain', 18, 'Minyak goreng secukupnya'),
(7, 'bahan', 1, '350 gr udang'),
(7, 'bahan', 2, '250 gr cumi'),
(7, 'bahan', 3, '300 gr kerang, rebus'),
(7, 'bahan', 4, 'Brokoli, rebus'),
(7, 'bumbu halus', 1, '10 siung bawang putih'),
(7, 'bumbu halus', 2, '10 siung bawang merah'),
(7, 'bumbu halus', 3, '8 buah cabai rawit merah'),
(7, 'bumbu halus', 4, 'Minyak secukupnya'),
(7, 'bahan lainnya', 1, '3 batang daun bawang, potong'),
(7, 'bahan lainnya', 2, '6 sdm saus tiram'),
(7, 'bahan lainnya', 3, '6 sdm saus tomat'),
(7, 'bahan lainnya', 4, '6 sdm saus sambal'),
(7, 'bahan lainnya', 5, '2 sdm kecap ikan'),
(7, 'bahan lainnya', 6, '1 sdm seasoning sauce'),
(7, 'bahan lainnya', 7, '800 ml air'),
(7, 'bahan lainnya', 8, '3 lembar daun salam'),
(7, 'bahan lainnya', 9, '4 lembar daun jeruk'),
(7, 'bahan lainnya', 10, '1 sdm gula pasir'),
(7, 'bahan lainnya', 11, '1/2 sdm kaldu bubuk'),
(8, 'bahan', 1, '1 kg daging bagian sengkel atau has dalam'),
(8, 'bahan', 2, '10 siung bawang putih, parut atau haluskan'),
(8, 'bahan', 3, '1 sdm garam'),
(8, 'bahan', 4, '1 sdm merica'),
(8, 'bahan', 5, '500 ml air'),
(8, 'bahan', 6, '300 gr cabe besar, keriting, rawit merah, tumbuk kasar'),
(8, 'bahan', 7, '200 gr bawang merah, tumbuk kasar'),
(8, 'bahan', 8, '2 sdm air jeruk nipis'),
(8, 'bahan', 9, '1/2 sdt gula pasir'),
(8, 'bahan', 10, '1 sdt garam'),
(9, 'bahan', 1, '500 gram hati ayam, cuci bersih'),
(9, 'bahan', 2, '2 butir kentang potong dadu'),
(9, 'bahan', 3, '1 gelas santan encer'),
(9, 'bahan', 4, 'Daun jeruk purut'),
(9, 'bahan', 5, 'Minyak untuk menumis'),
(9, 'bumbu halus', 1, '1 shallot ukuran besar (5 siung bawang merah)'),
(9, 'bumbu halus', 2, '4 siung bawang putih'),
(9, 'bumbu halus', 3, '1 cabe merah besar'),
(9, 'bumbu halus', 4, 'Cabe rawit sesuai selera'),
(9, 'bumbu halus', 5, '1 sdt gula merah (optional)'),
(9, 'bumbu halus', 6, '2 butir kemiri (optional)'),
(9, 'bumbu halus', 7, 'Garam dan gula secukupnya'),
(9, 'bumbu halus', 8, 'Penyedap rasa secukupnya'),
(10, 'bahan', 1, '1 ekor ayam/ 500 gr daging sapi atau hati ayam'),
(10, 'bumbu halus', 1, '2 sdt ketumbar bubuk'),
(10, 'bumbu halus', 2, '1 sdt kunyit bubuk'),
(10, 'bumbu halus', 3, '4 siung bawang putih tumbuk kasar bersama kulitnya'),
(10, 'bumbu halus', 4, 'Garam'),
(10, 'bumbu halus', 5, 'Penyedap'),
(11, 'bahan gudeg', 1, '1 kg nangka muda boleh kaleng, or frozen'),
(11, 'bahan gudeg', 2, '100-150 gr kithul jaggery / gula jawa'),
(11, 'bahan gudeg', 3, 'Ceker ayam (hard-chicken)'),
(11, 'bahan gudeg', 4, '10 sachet black tea (pengganti daun jati)'),
(11, 'bahan gudeg', 5, '1 liter santan instan'),
(11, 'bahan gudeg', 6, 'Air secukupnya'),
(11, 'bumbu halus gudeg', 1, '50 gram bawang merah/shallot'),
(11, 'bumbu halus gudeg', 2, '4 siung bawang putih/garlic'),
(11, 'bumbu halus gudeg', 3, '8 butir candlenut/kemiri'),
(11, 'bumbu halus gudeg', 4, '1 sendok teh coriander/ketumbar'),
(11, 'bumbu rempah gudeg', 1, '6 lembar bayleaves/daun salam'),
(11, 'bumbu rempah gudeg', 2, '3 cm galangal/lengkuas'),
(11, 'bumbu rempah gudeg', 3, '2 batang lemongrass/sereh, memarkan/digeprek/digepuk'),
(11, 'bumbu rempah gudeg', 4, '3 lembar keffir lime leaves/daun jeruk purut, disobek-sobek'),
(11, 'sambal krecek - bahan sambal goreng', 1, '50 gram krecek yang bagus'),
(11, 'sambal krecek - bahan sambal goreng', 2, '100 gram black eyed peas/kacang tholo'),
(11, 'sambal krecek - bahan sambal goreng', 3, '200 gram tempe potong kotak kecil'),
(11, 'sambal krecek - bumbu sambal goreng', 1, '8 butir bawang merah, iris tipis'),
(11, 'sambal krecek - bumbu sambal goreng', 2, '3 siung bawang putih, iris tipis'),
(11, 'sambal krecek - bumbu sambal goreng', 3, 'Cabai merah sesuai selera dihaluskan (disarankan cabai keriting/bird''s eye chilli/thai chilli)'),
(11, 'opor ayam - bahan', 1, '1 ekor ayam pejantan/ayam kampung/free range/murghi'),
(11, 'opor ayam - bahan', 2, '5 buah tahu/firm tofu'),
(11, 'opor ayam - bahan', 3, '3 butir telur rebus'),
(11, 'opor ayam - bahan', 4, '800-1000 ml santan'),
(11, 'opor ayam - bumbu halus', 1, '8 butir bawang merah'),
(11, 'opor ayam - bumbu halus', 2, '4 butir kemiri'),
(11, 'opor ayam - bumbu halus', 3, '3 siung bawang putih'),
(11, 'opor ayam - bumbu halus', 4, '1/2 sendok teh ketumbar'),
(11, 'opor ayam - bumbu rempah', 1, '2 lembar daun salam'),
(11, 'opor ayam - bumbu rempah', 2, '1 sereh'),
(11, 'opor ayam - bumbu rempah', 3, '1 cm lengkuas'),
(11, 'opor ayam - bumbu rempah', 4, '1 lembar daun jeruk purut'),
(12, 'bahan', 1, '2 fillet seabass/cod'),
(12, 'bahan', 2, '5 sdm tepung terigu'),
(12, 'bahan', 3, '1 sdm garlic powder'),
(12, 'bahan', 4, '1 sdt garam'),
(12, 'bahan sambal dabu dabu', 1, '10 buah tomat cherry merah'),
(12, 'bahan sambal dabu dabu', 2, '5 siung bawang merah'),
(12, 'bahan sambal dabu dabu', 3, '3 lembar irisan daun jeruk (opsional)'),
(12, 'bahan sambal dabu dabu', 4, '120ml minyak goreng'),
(12, 'bahan sambal dabu dabu', 5, '1 sdm air perasan jeruk nipis'),
(12, 'bahan sambal dabu dabu', 6, '1/2 sdt gula pasir'),
(12, 'bahan sambal dabu dabu', 7, '1 sdt garam'),
(13, 'bahan', 1, '1 atau 2 buah ayam utuh (whole chicken) dengan ukuran sedang'),
(13, 'bahan', 2, '1 liter santan/coconut milk'),
(13, 'bahan', 3, '1 buah serai/lemon grass diambil bawahnya yang putih digeprek'),
(13, 'bahan', 4, '5 cm laos/lengkuas/galangal'),
(13, 'bahan', 5, '4 lembar daun salam (substitut: bay leaf)'),
(13, 'bahan', 6, '8 buah bawang merah/shallot'),
(13, 'bahan', 7, '8 buah/siung bawang putih/garlic'),
(13, 'bahan', 8, '3 buah cabai merah/red chilli'),
(13, 'bahan', 9, '10 butir kemiri/candle nut'),
(13, 'bahan', 10, '1 sendok teh jinten/cumin'),
(13, 'bahan', 11, '1 sendok teh ketumbar/coriander'),
(13, 'bahan', 12, '1 sendok makan penuh gula merah yang sudah diiris tipis/Java Sugar-Palm Sugar'),
(13, 'bahan', 13, '1 sendok makan garam/salt'),
(14, 'bahan', 1, '250 gr daging ayam giling'),
(14, 'bahan', 2, '250 gr daging sapi giling'),
(14, 'bahan', 3, '3 lbr roti tawar, rendam dalam air lalu remas'),
(14, 'bahan', 4, '2 btr telur ayam'),
(14, 'bahan', 5, '1 sdt gula'),
(14, 'bahan', 6, '1 sdt garam'),
(14, 'bahan', 7, '1 sdt lada'),
(14, 'bahan', 8, '1 sdt kaldu bubuk'),
(14, 'bahan', 9, '1/2 sdt pala bubuk'),
(14, 'bahan', 10, '2 bh wortel/sosis'),
(15, 'bahan', 1, 'Iga kambing muda - lamb, secukupnya'),
(15, 'bumbu halus', 1, '4 siung bawang putih'),
(15, 'bumbu halus', 2, '2 siung bawang merah'),
(15, 'bumbu halus', 3, '1 sendok teh ketumbar'),
(15, 'bumbu halus', 4, '3 butir kemiri'),
(15, 'bumbu halus', 5, '3 sendok makan kecap manis'),
(15, 'bumbu halus', 6, '1 sendok makan oyster sauce'),
(15, 'bumbu halus', 7, '1 sendok teh vinegar'),
(15, 'bumbu halus', 8, 'Garam secukupnya'),
(16, 'bahan', 1, '3 ons daging kambing pilih bagian yang empuk diiris tipis-tipis seperti daging sukiyaki'),
(16, 'bahan', 2, '1 butir telur dikocok dan ditambahkan sedikit air'),
(16, 'bahan', 3, '1 butir bawang bombay ukuran sedang diiris cincin'),
(16, 'bahan', 4, '2 buah tomat buah digiling halus'),
(16, 'bahan', 5, '1 sdt oregano'),
(16, 'bahan', 6, '50 cc susu cair'),
(17, 'bahan', 1, '3 buah kentang yang paling besar atau 5 yang medium, direbus dan dihancurkan'),
(17, 'bahan', 2, '1 kaleng tuna (250gr) (pakai yang di sunflower oil), ditiriskan air/minyaknya, daging ikan dihancurkan'),
(17, 'bahan', 3, '1 sdt butter/margarine'),
(17, 'bahan', 4, 'Garam secukupnya'),
(17, 'bahan', 5, 'Pala bubuk secukupnya'),
(17, 'bahan', 6, 'Merica bubuk secukupnya'),
(17, 'bahan', 7, '1 batang bawang prei, diiris halus'),
(17, 'bahan', 8, '1 sendok teh bawang merah goreng (optional)'),
(17, 'bahan', 9, '1 siung bawang putih, dihancurkan'),
(17, 'bahan', 10, '1 sdm tepung terigu (plain flour)'),
(17, 'bahan', 11, '1 kuning telur (optional)'),
(17, 'bahan', 12, '1-2 putih telur dikocok sebentar'),
(17, 'tips', 1, 'Jangan merebus kentang kelamaan, tiriskan dan hancurkan kentang sewaktu masih panas dengan garpu/alat khusus mash potato atau gelas.'),
(17, 'tips', 2, 'Jangan mengaduk adonan terlalu lama, secampurnya saja.'),
(17, 'tips', 3, 'Menggoreng dengan minyak yang panas dan sebentar saja.'),
(17, 'tips', 4, 'Jangan terlalu banyak memasukkan adonan ke penggorengan, cukup 5-6 buah saja di frypan berdiameter 20cm.'),
(17, 'tips', 5, 'Jika adonan ditambahkan kuning telur, adonan akan menjadi lebih lembut dan berkesan moist.'),
(17, 'tips', 6, 'Ikan tuna dapat diganti dengan ikan jenis lain tetapi yang telah dikukus/masak dulu baru dihancurkan, atau kornet/daging cincang masak.'),
(17, 'tips', 7, 'Untuk variasi, dalam adonan dapat ditambahkan coriander bubuk/daun coriander yang telah dipotong halus, irisan rebusan wortel, dll tergantung selera.'),
(18, 'bahan', 1, 'Tempe dipotong kecil/dadu dikukus dulu'),
(18, 'bahan', 2, 'Spring green secukupnya dipotong-potong kasar'),
(18, 'bahan', 3, 'Tomat dipotong jadi 4 or 6 slice'),
(18, 'bahan', 4, 'Serai, daun jeruk, daun salam secukupnya'),
(18, 'bahan', 5, 'Ikan teri yang kecil tipis atau yang utuh seperti ikan bilis'),
(18, 'bahan', 6, 'Santan kelapa/1.5 or satu kaleng'),
(18, 'bahan', 7, 'Satu butir telur dikocok dahulu'),
(18, 'bahan', 8, 'Petai secukupnya'),
(18, 'bahan', 9, 'Cabai hijau potong kasar'),
(18, 'bahan', 10, 'Daun bawang/spring onion sesuai selera, kemudian diiris kasar'),
(18, 'bahan', 11, 'Daun pisang untuk membungkus atau alumunium foil'),
(18, 'bumbu halus', 1, 'Bawang merah'),
(18, 'bumbu halus', 2, 'Bawang putih'),
(18, 'bumbu halus', 3, 'Kemiri'),
(18, 'bumbu halus', 4, 'Ketumbar'),
(18, 'bumbu halus', 5, 'Kencur'),
(18, 'bumbu halus', 6, 'Jinten'),
(18, 'bumbu halus', 7, 'Jahe'),
(18, 'bumbu halus', 8, 'Terasi (shrimp paste)'),
(18, 'bumbu halus', 9, 'Garam'),
(18, 'bumbu halus', 10, 'Kaldu block/sedikit saja'),
(19, 'bahan', 1, '1 pak curly kale atau spring cabbage, cuci bersih'),
(19, 'bumbu saus', 1, 'Gula jawa disisir, kira-kira 2 sendok makan penuh'),
(19, 'bumbu saus', 2, 'Garam secukupnya'),
(19, 'bumbu saus', 3, '3 mata asam'),
(19, 'bumbu saus', 4, '1/2 sendok teh terasi'),
(19, 'bumbu saus', 5, '4 siung bawang merah'),
(19, 'bumbu saus', 6, 'Cabe rawit secukupnya'),
(19, 'bumbu saus', 7, '1/2 gelas air'),
(20, 'bahan', 1, '1 bungkus daun Kai Choi (800gram)'),
(20, 'bahan', 2, '200 gram udang, kupas dan belah tengah'),
(20, 'bahan', 3, '2 tahu potong kecil dan goreng'),
(20, 'bahan', 4, '2 bawang bombay ukuran sedang, iris'),
(20, 'bahan', 5, '2 bawang putih, iris'),
(20, 'bahan', 6, '1 sdm kecap asin/light soy sauce'),
(20, 'bahan', 7, '2 sdm oyster sauce'),
(20, 'bahan', 8, 'Garam secukupnya'),
(20, 'bahan', 9, 'Merica halus'),
(20, 'bahan', 10, 'Air panas sedikit'),
(21, 'bahan kuah', 1, '2 liter air kaldu ayam kampung (bisa diganti kaldu hen)'),
(21, 'bahan kuah', 2, '1 buah bawang bombay, cincang kasar'),
(21, 'bahan kuah', 3, '4 siung bawang putih, memarkan'),
(21, 'bahan kuah', 4, '1/2 sendok teh lada putih'),
(21, 'bahan kuah', 5, 'Garam dan gula pasir secukupnya'),
(21, 'bahan kuah', 6, 'Minyak untuk menumis'),
(21, 'bahan ayam bungkus telor', 1, '15 lembar dadar telor (dari 3 butir telur + 1 sendok makan maizena + 50 cc air)'),
(21, 'bahan ayam bungkus telor', 2, '250 gram daging ayam cincang'),
(21, 'bahan ayam bungkus telor', 3, '1-2 butir telor'),
(21, 'bahan ayam bungkus telor', 4, '1 buah wortel, parut'),
(21, 'bumbu haluskan', 1, '4 batang daun bawang, iris halus'),
(21, 'bumbu haluskan', 2, '1 buah bawang bombay, cincang halus'),
(21, 'bumbu haluskan', 3, '2 siung bawang putih, haluskan'),
(21, 'bumbu haluskan', 4, '1/2 sendok teh lada putih'),
(21, 'bumbu haluskan', 5, '1 sendok teh peres garam'),
(21, 'bumbu haluskan', 6, '1 sendok teh gula pasir'),
(21, 'bahan pelengkap', 1, 'Wortel kukus'),
(21, 'bahan pelengkap', 2, 'Kacang polong kukus'),
(21, 'bahan pelengkap', 3, 'Jamur putih yang telah direndam air panas'),
(21, 'bahan pelengkap', 4, 'Irisan daun bawang/seledri'),
(22, 'bahan kuah', 1, '750 gram iga kambing, potong sedang/kasar'),
(22, 'bahan kuah', 2, 'Air untuk merebus'),
(22, 'bahan kuah', 3, '3 cm jahe potong, memarkan'),
(22, 'bahan kuah', 4, 'Garam'),
(22, 'bahan kuah', 5, 'Minyak sayur untuk menumis bumbu'),
(22, 'bahan kuah', 6, 'Batang kulit kayu manis secukupnya'),
(22, 'bahan kuah', 7, '5 butir cengkeh'),
(22, 'bahan kuah', 8, 'Wortel dipotong-potong bundar'),
(22, 'bahan kuah', 9, 'Brokoli dipotong kecil'),
(22, 'bahan kuah', 10, 'Tomat merah dipotong membujur menjadi 8 bagian'),
(22, 'bahan kuah', 11, 'Daun bawang ambil bagian putihnya, potong-potong 2 cm'),
(22, 'bumbu haluskan', 1, '8 butir bawang merah'),
(22, 'bumbu haluskan', 2, '3 siung bawang putih'),
(22, 'bumbu haluskan', 3, '1 sdt merica butiran'),
(22, 'bumbu haluskan', 4, '1 sdt garam'),
(22, 'taburan dan pelengkap', 1, 'Bawang merah goreng'),
(22, 'taburan dan pelengkap', 2, 'Seledri cincang'),
(22, 'taburan dan pelengkap', 3, 'Sambal rawit merah'),
(22, 'taburan dan pelengkap', 4, 'Emping goreng'),
(23, 'bahan', 1, '1 ekor ayam'),
(23, 'bahan', 2, '2 liter air'),
(23, 'bumbu halus', 1, '10 bawang putih yang sudah digoreng'),
(23, 'bumbu halus', 2, '5 bawang merah (shallot)'),
(23, 'bumbu halus', 3, '1/2 sdt jahe'),
(23, 'bumbu halus', 4, '1/2 sdt pala bubuk'),
(23, 'bumbu halus', 5, '1/2 sdt merica'),
(23, 'bumbu cemplung', 1, '1/4 sdt kayu manis'),
(23, 'bumbu cemplung', 2, '5 cengkeh'),
(23, 'bumbu cemplung', 3, '3 kapulaga (cardamom)'),
(23, 'bumbu cemplung', 4, '2 bunga lawang (star anise)'),
(23, 'bumbu cemplung', 5, '3 tangkai daun bawang yang diiris'),
(23, 'bumbu cemplung', 6, '1 tangkai seledri'),
(23, 'bumbu cemplung', 7, '1 bawang bombay besar'),
(23, 'bumbu cemplung', 8, '3 sdt garam'),
(23, 'bumbu cemplung', 9, '2 sdt kaldu bubuk'),
(23, 'bumbu cemplung', 10, '1/2 sdt gula'),
(24, 'bahan', 1, '1 kg ikan tilapia'),
(24, 'bahan', 2, '1 buah jeruk nipis'),
(24, 'bahan', 3, '4 sendok makan kecap manis'),
(24, 'bahan', 4, '2 sendok makan butter, lelehkan'),
(24, 'bahan', 5, 'Garam secukupnya'),
(24, 'bumbu halus', 1, '4 siung bawang putih'),
(24, 'bumbu halus', 2, '1 siung bawang merah (bisa pakai red onion)'),
(24, 'bumbu halus', 3, '1 ruas jahe'),
(24, 'bumbu halus', 4, '2 buah cabe merah besar/sesuai selera'),
(25, 'bahan', 1, '5 siung bawang putih, cincang kasar'),
(25, 'bahan', 2, '5 buah bakso ikan, iris'),
(25, 'bahan', 3, '200 gr dada ayam'),
(25, 'bahan', 4, 'Wortel'),
(25, 'bahan', 5, 'Pakcoy/sawi putih/green/sweet heart cabbage/white cabbage'),
(25, 'bahan', 6, 'Baby corn'),
(25, 'bahan', 7, 'Jamur'),
(25, 'bahan', 8, '150gr tepung plain'),
(25, 'bahan', 9, '1/2 sendok teh lada bubuk'),
(25, 'bahan', 10, '1 sendok makan oyster sauce'),
(25, 'bahan', 11, '1 sendok makan kecap manis'),
(25, 'bahan', 12, 'Garam secukupnya'),
(26, 'bahan', 1, '500gr ceker ayam'),
(26, 'bahan', 2, '1 sendok makan oyster sauce'),
(26, 'bahan', 3, '2 sendok makan kecap manis'),
(26, 'bahan', 4, '1 ruas lengkuas'),
(26, 'bahan', 5, '2 lembar daun jeruk'),
(26, 'bahan', 6, '1 batang serai'),
(26, 'bahan', 7, '400ml air'),
(26, 'bahan', 8, 'Garam secukupnya'),
(26, 'bumbu halus', 1, '2 buah cabai merah besar'),
(26, 'bumbu halus', 2, '6 buah cabai merah rawit'),
(26, 'bumbu halus', 3, '4 siung shallot'),
(26, 'bumbu halus', 4, '4 siung bawang putih'),
(27, 'bahan', 1, '5 butir telur ayam'),
(27, 'bahan', 2, '200 ml santan kental'),
(27, 'bahan', 3, '3/4 sendok teh lada'),
(27, 'bahan', 4, 'Garam secukupnya'),
(27, 'bumbu halus', 1, '2 buah cabai merah besar'),
(27, 'bumbu halus', 2, '4 siung shallot'),
(27, 'bumbu halus', 3, '3 siung bawang putih'),
(27, 'bumbu halus', 4, '1 buah tomat'),
(28, 'bahan telor dadar', 1, '4 butir telur ayam'),
(28, 'bahan telor dadar', 2, '2 siung shallot'),
(28, 'bahan telor dadar', 3, '2 siung bawang putih'),
(28, 'bahan telor dadar', 4, '1 buah cabai besar'),
(28, 'bahan telor dadar', 5, '1 sendok makan desicated coconut'),
(28, 'bahan telor dadar', 6, '2 sendok makan tepung beras'),
(28, 'bahan telor dadar', 7, '1/2 sendok teh kunyit'),
(28, 'bahan telor dadar', 8, '1/2 sendok teh lada bubuk'),
(28, 'bahan telor dadar', 9, 'Daun bawang'),
(28, 'bahan telor dadar', 10, 'Garam secukupnya'),
(28, 'bahan sambal ijo', 1, '15 buah cabai hijau'),
(28, 'bahan sambal ijo', 2, '1 buah red onion'),
(28, 'bahan sambal ijo', 3, '5 siung bawang putih'),
(28, 'bahan sambal ijo', 4, '1 sendok teh lada bubuk'),
(28, 'bahan sambal ijo', 5, '1 sendok teh garam'),
(29, 'bahan', 1, '2 buah pare'),
(29, 'bahan', 2, '1 genggam teri, goreng'),
(29, 'bahan', 3, '4 buah cabai hijau, iris serong'),
(29, 'bahan', 4, '1 buah red onion, iris tipis'),
(29, 'bahan', 5, '3 siung bawang putih, iris tipis'),
(29, 'bahan', 6, '1 sendok teh garam'),
(29, 'bahan', 7, '1 sendok teh gula'),
(29, 'bahan', 8, '100 ml air'),
(30, 'bahan', 1, '1 genggam spaghetti'),
(30, 'bahan', 2, '5 siung bawang putih, cincang halus'),
(30, 'bahan', 3, '200gr dada ayam, potong dadu'),
(30, 'bahan', 4, '1 sendok makan oyster sauce'),
(30, 'bahan', 5, '2 sendok makan kecap manis'),
(30, 'bahan', 6, 'Daun bawang, iris'),
(30, 'bahan', 7, '1/2 sendok teh lada bubuk'),
(31, 'bahan', 1, '1/2 kg chicken mince'),
(31, 'bahan', 2, '250gr ceker ayam'),
(31, 'bahan', 3, 'Mie shanghai, rebus'),
(31, 'bahan', 4, '2 batang daun bawang'),
(31, 'bahan', 5, '2 sendok makan kecap manis'),
(31, 'bahan', 6, '1 sendok makan oyster sauce'),
(31, 'bahan', 7, '1 1/2 sendok teh lada bubuk'),
(31, 'bahan', 8, '3 lembar daun jeruk'),
(31, 'bahan', 9, '1 batang sereh'),
(31, 'bahan', 10, '1 ruas lengkuas'),
(31, 'bahan', 11, 'Garam secukupnya'),
(31, 'bahan', 12, '500ml air'),
(31, 'bumbu halus', 1, '1 buah red onion ukuran besar'),
(31, 'bumbu halus', 2, '5 siung bawang putih'),
(31, 'bumbu halus', 3, '1 sendok teh ketumbar bubuk'),
(31, 'bumbu halus', 4, '1/2 sendok teh kunyit bubuk'),
(31, 'bumbu halus', 5, '1 ruas jahe'),
(31, 'pelengkap', 1, 'Pakcoy rebus'),
(31, 'pelengkap', 2, 'Bakso daging/bakso ikan'),
(31, 'pelengkap', 3, 'Pangsit rebus/goreng'),
(31, 'pelengkap', 4, 'Irisan daun bawang'),
(31, 'pelengkap', 5, 'Bawang goreng'),
(32, 'bahan a', 1, '500 gr santan (kekentalan sedang)'),
(32, 'bahan a', 2, '5 sdm tepung terigu'),
(32, 'bahan a', 3, '1 sdt garam'),
(32, 'bahan a', 4, '6 sdm gula pasir'),
(32, 'bahan b', 1, '250 gr santan'),
(32, 'bahan b', 2, '2,5 sdm tepung jagung'),
(32, 'bahan b', 3, '2 sdm gula pasir'),
(32, 'bahan b', 4, '1 sdt garam'),
(32, 'bahan b', 5, 'Pasta pandan sesuai selera'),
(32, 'bahan c', 1, '250 gr santan'),
(32, 'bahan c', 2, '1 biji telur'),
(32, 'bahan c', 3, '140 gr tepung terigu'),
(32, 'bahan c', 4, '4 sdm gula pasir'),
(32, 'bahan d', 1, 'Cetakan kue'),
(32, 'bahan d', 2, 'Minyak sayur'),
(33, 'bahan', 1, 'Kolang-kaling/palm fruit'),
(33, 'bahan', 2, 'Avocado, dipotong dadu'),
(33, 'bahan', 3, 'Nangka manis (segar atau kalengan), dipotong dadu'),
(33, 'bahan', 4, 'Kelapa muda/potongan kelapa berbentuk parutan kasar'),
(33, 'bahan', 5, 'Nata de coco'),
(33, 'bahan', 6, 'Susu semi skim'),
(33, 'bahan', 7, 'Syrup mawar/Rose Syrup merk East Ends'),
(33, 'bahan', 8, 'Es batu - crushed es batu'),
(33, 'bahan', 9, 'Garam sedikit'),
(33, 'penyajian buah fresh', 1, 'Siapkan semua buah-buahan segar.'),
(33, 'penyajian buah fresh', 2, 'Semua potongan buah serta kolang-kaling, nata de coco, serutan kelapa, dan lainnya, dimasukkan ke dalam bowl.'),
(33, 'penyajian buah fresh', 3, 'Dimasukkan susu kental manis, syrup, susu biasanya, kalau mau lebih manis dimasukkan pula air gula putih.'),
(33, 'penyajian buah fresh', 4, 'Tambahkan sedikit garam.'),
(33, 'penyajian buah fresh', 5, 'Baru dimasukkan es batu yang sudah di crushed/remuk-kan, dan diaduk.'),
(34, 'bahan', 1, 'Nanas 1 buah (potong sesuai selera)'),
(34, 'bahan', 2, 'Cocktail in syrup 2 kaleng (@250gr), gunakan buahnya saja'),
(34, 'bahan', 3, 'Gula pasir 10 sdm'),
(34, 'bahan', 4, 'Cengkeh 10 butir'),
(34, 'bahan', 5, 'Kayu manis 1 batang sedang'),
(34, 'bahan', 6, 'Air 1 liter'),
(34, 'bahan', 7, 'Chia seed 3 sdm, rendam air panas'),
(35, 'bahan', 1, '4 lembar roti tawar'),
(35, 'bahan', 2, '2 buah pisang (potong 2 bagian)'),
(35, 'bahan', 3, 'Nutella'),
(35, 'bahan', 4, 'Keju parut'),
(35, 'bahan', 5, 'Butter'),
(35, 'bahan', 6, 'Topping (optional): wijen/keju/bubuk kayu manis/madu'),
(36, 'bahan', 1, '1 pack deep fried tofu (biasanya ada di oriental shop)'),
(36, 'bahan', 2, '5 buah bawang merah'),
(36, 'bahan', 3, '3 buah cabai rawit'),
(36, 'bahan kuah', 1, '350 ml air'),
(36, 'bahan kuah', 2, '125 gr gula merah'),
(36, 'bahan kuah', 3, '1/2 sdt asam jawa (bisa diganti dengan 1/2 sdt tamarind paste)'),
(36, 'bahan kuah', 4, '7 sdm kecap manis'),
(36, 'bahan kuah', 5, 'Sejumput garam'),
(37, 'bahan', 1, '900 gram soft cheese'),
(37, 'bahan', 2, '350 gram gula halus (caster sugar)'),
(37, 'bahan', 3, '7 butir telur'),
(37, 'bahan', 4, '500 ml double cream atau heavy cream'),
(37, 'bahan', 5, '4 sendok makan tepung terigu'),
(38, 'bahan', 1, '5 butir telur'),
(38, 'bahan', 2, '150 gr gula pasir butiran halus (bisa ditambah jika suka manis)'),
(38, 'bahan', 3, '300-350 gr pisang tanduk (biasanya tersedia di Asian store) atau pisang biasa, dihaluskan'),
(38, 'bahan', 4, '225 gr tepung terigu'),
(38, 'bahan', 5, '25 gr maizena'),
(38, 'bahan', 6, '1/2 sdt bubuk kayu manis'),
(38, 'bahan', 7, '1/2 sdt soda kue'),
(38, 'bahan', 8, '160 gr minyak sayur/180 gr butter dilelehkan'),
(39, 'bahan', 1, '1 sheet puff pastry'),
(39, 'bahan', 2, '3 ripe banana (pisang matang)'),
(39, 'bahan', 3, '2 spoons of butter'),
(39, 'bahan', 4, '400 gr mature cheese'),
(39, 'bahan', 5, '12 tsp of Nutella'),
(39, 'bahan', 6, '2 egg yolk'),
(40, 'bahan', 1, '339 gr ubi manis (sweet potato)'),
(40, 'bahan', 2, '125 gr tepung ketan'),
(40, 'bahan', 3, '100 gr gula merah'),
(40, 'bahan', 4, 'Kelapa parut kering (basah) secukupnya'),
(40, 'bahan', 5, 'Air untuk merebus secukupnya'),
(41, 'bahan isian kelapa unti kelapa', 1, '200 gram kelapa parut (bisa memilih desiccated coconut atau shredded coconut)'),
(41, 'bahan isian kelapa unti kelapa', 2, '100 gram gula merah/gula aren'),
(41, 'bahan isian kelapa unti kelapa', 3, '1 sendok makan gula pasir'),
(41, 'bahan isian kelapa unti kelapa', 4, '1 sendok teh garam'),
(41, 'bahan isian kelapa unti kelapa', 5, 'Daun pandan satu lembar'),
(41, 'bahan isian kelapa unti kelapa', 6, '100 ml air matang atau santan'),
(41, 'bahan kulit', 1, '1 butir telur'),
(41, 'bahan kulit', 2, '65 ml santan'),
(41, 'bahan kulit', 3, '265 ml air matang'),
(41, 'bahan kulit', 4, '125 gram tepung protein sedang atau plain flour'),
(41, 'bahan kulit', 5, '1 sendok teh gula pasir'),
(41, 'bahan kulit', 6, 'Sejumput garam'),
(41, 'bahan kulit', 7, 'Pewarna makanan hijau, kuning, merah muda dan biru'),
(42, 'bahan', 1, '400g tepung ketan'),
(42, 'bahan', 2, '150g margarine/butter'),
(42, 'bahan', 3, '3 butir telur'),
(42, 'bahan', 4, '1 butir kuning telur'),
(42, 'bahan', 5, '250g gula'),
(42, 'bahan', 6, '250g desicated coconut/kelapa parut'),
(42, 'bahan', 7, '1.5 kaleng santan'),
(42, 'bahan', 8, 'Vanili bubuk secukupnya'),
(43, 'bahan kulit', 1, '5 butir telur'),
(43, 'bahan kulit', 2, '125 ml santan'),
(43, 'bahan kulit', 3, '1/4 sdt garam'),
(43, 'bahan isian', 1, '200 gr daging cincang'),
(43, 'bahan isian', 2, '1 btr telur'),
(43, 'bahan isian', 3, '3 sdm santan kental'),
(43, 'bumbu halus', 1, '5 siung bawang merah'),
(43, 'bumbu halus', 2, '3 siung bawang putih'),
(43, 'bumbu halus', 3, '1 sdt ketumbar'),
(43, 'bumbu halus', 4, '1/4 sdt jinten'),
(43, 'bumbu halus', 5, '3 butir kemiri'),
(43, 'bumbu halus', 6, '1 sdt garam'),
(44, 'bahan', 1, '500 gr potatoes, fried then mashed (kentang, digoreng lalu dihaluskan)'),
(44, 'bahan', 2, '50 gr butter melted'),
(44, 'bahan', 3, '2 eggs, separate egg yolk n white'),
(44, 'bahan', 4, '100 gr flour'),
(44, 'bahan', 5, '1 tbsp milk powder'),
(44, 'bahan', 6, 'Salt, pepper, nutmeg, sugar to taste'),
(44, 'bahan', 7, '200 gr carrots, finely cubed'),
(44, 'bahan', 8, '150 gr minced chicken'),
(44, 'bahan', 9, '1 medium onion finely chopped'),
(44, 'bahan', 10, '2 cloves garlic crushed'),
(44, 'bahan', 11, '1 bunch spring onions'),
(44, 'bahan', 12, 'Bread crumbs'),
(44, 'bahan', 13, 'Oil for frying'),
(45, 'bahan', 1, '3 kuning telur'),
(45, 'bahan', 2, '1 putih telur'),
(45, 'bahan', 3, '180 gr caster sugar'),
(45, 'bahan', 4, '500 ml santan'),
(45, 'bahan', 5, '500 gr kentang direbus dan dihaluskan'),
(45, 'bahan', 6, '150 gr plain flour'),
(45, 'bahan', 7, '150 gr raisin / alternatif lain nangka manis'),
(45, 'bahan', 8, 'Garam sejumput'),
(45, 'bahan', 9, 'Minyak/mentega untuk loyang'),
(46, 'bahan a topping', 1, '350 gr santan/coconut milk'),
(46, 'bahan a topping', 2, '4 eggs/telur'),
(46, 'bahan a topping', 3, '100 gr flour'),
(46, 'bahan a topping', 4, '280 gr granulated sugar'),
(46, 'bahan a topping', 5, '6 lembar pandan/pandan leaves (diblender kemudian diperas airnya untuk warna dan aroma)'),
(46, 'bahan b base', 1, '350 gr coconut milk/santan'),
(46, 'bahan b base', 2, '225 gr glutinous rice/ketan putih'),
(46, 'bahan b base', 3, '1 tsp salt/garam dicampur dengan santan'),
(47, 'bahan a topping', 1, '4 butir telur'),
(47, 'bahan a topping', 2, '200 gr gula merah iris halus (bisa pakai soft dark brown sugar)'),
(47, 'bahan a topping', 3, '500 cc santan kental'),
(47, 'bahan a topping', 4, '200 gr tepung beras'),
(47, 'bahan a topping', 5, '50 gram coklat bubuk'),
(47, 'bahan b base', 1, '750gr beras ketan'),
(47, 'bahan b base', 2, '1 sendok teh garam'),
(47, 'bahan b base', 3, '100ml santan'),
(48, 'bahan', 1, '1 kg singkong/cassava'),
(48, 'bahan', 2, '120 gr palm sugar/gula malaka'),
(48, 'bahan', 3, '50 gr gula pasir (sesuai selera)'),
(48, 'bahan', 4, '100gr desicated coconut/kelapa parut'),
(48, 'bahan', 5, '1 bungkus vanili (5gr)'),
(49, 'bahan ketan', 1, '500 gr beras ketan, cuci, rendam sedikitnya 2 jam'),
(49, 'bahan ketan', 2, '1 sendok teh pasta pandan (optional)'),
(49, 'bahan ketan', 3, '600 ml santan'),
(49, 'bahan ketan', 4, '3/4 sendok teh garam'),
(49, 'bahan ketan', 5, '3 lembar daun pandan'),
(49, 'bahan unti kelapa', 1, '200 gr gula merah/gula malaka/palm sugar'),
(49, 'bahan unti kelapa', 2, '200 ml air'),
(49, 'bahan unti kelapa', 3, '3 lembar daun pandan'),
(49, 'bahan unti kelapa', 4, '1/2 sendok teh garam'),
(49, 'bahan unti kelapa', 5, '1/4 sendok teh vanili bubuk'),
(49, 'bahan unti kelapa', 6, '250 gr kelapa parut/desicated coconut'),
(50, 'bahan', 1, '200 gram tepung ketan'),
(50, 'bahan', 2, '200 ml air'),
(50, 'bahan', 3, 'Pasta pandan, secukupnya'),
(50, 'bahan', 4, 'Gula merah/gula malaka/palm sugar sisir halus, secukupnya'),
(50, 'bahan', 5, 'Kelapa parut/desicated coconut'),
(50, 'bahan', 6, '3/4 sendok teh garam'),
(51, 'bahan', 1, 'Kulit lumpia/kulit spring roll'),
(51, 'bahan', 2, '200gr daging cincang (sapi/kambing)'),
(51, 'bahan', 3, '4 butir telur'),
(51, 'bahan', 4, '1 buah bawang bombay, cacah kasar'),
(51, 'bahan', 5, 'Daun bawang, iris'),
(51, 'bahan', 6, '1 sendok teh garlic powder'),
(51, 'bahan', 7, '1 sendok teh ketumbar bubuk'),
(51, 'bahan', 8, '1/2 sendok teh jintan'),
(51, 'bahan', 9, 'Garam secukupnya'),
(52, 'bahan', 1, '2 mangga'),
(52, 'bahan', 2, '1 buah nanas besar'),
(52, 'bahan', 3, '2 buah ketela pohon/sweet potatoes'),
(52, 'bahan', 4, '3 buah apel / 3 cooking apple/grannysmith apple'),
(52, 'bahan', 5, '2 buah cucumber/ketimun'),
(52, 'bahan', 6, '250 gr brown sugar/gula jawa'),
(52, 'bahan', 7, '5 red chillies/cabai merah keriting'),
(52, 'bahan', 8, '1 tsp terasi/shrimp paste'),
(52, 'bahan', 9, '1 tsp salt'),
(52, 'bahan', 10, '2 tbsp tamarind juice/asam');

-- ---------------------------------------------------------
-- Data: langkah
-- ---------------------------------------------------------
INSERT INTO `langkah` (`resep_id`, `grup`, `urutan`, `instruksi`) VALUES
(1, 'cara memasak', 1, 'Marinasi ayam dengan jeruk nipis dan garam selama kurang lebih 20 menit, lalu cuci bersih. Sisihkan.'),
(1, 'cara memasak', 2, 'Panaskan minyak di atas wajan besar, lalu tumis bumbu halus hingga harum.'),
(1, 'cara memasak', 3, 'Tuang santan. Aduk lalu rebus hingga mendidih.'),
(1, 'cara memasak', 4, 'Masukkan ayam. Masak hingga matang dan bumbu meresap. Matikan kompor.'),
(1, 'cara memasak', 5, 'Panggang ayam di atas bara api atau dalam oven api atas di temperatur 200 derajat celcius, posisi loyang nomer 2 dari atas. Sambil oles dengan bumbu yang tersisa, panggang hingga bumbu sedikit terbakar. Balik ayam, lakukan hal yang sama.'),
(1, 'cara memasak', 6, 'Jika sudah agak terbakar kedua sisi, keluarkan dari oven. Sajikan dengan lalapan, sambel cobek, dan nasi hangat.'),
(2, 'cara memasak', 1, 'Bakso: Iris bawang putih dan bawang merah, lalu goreng hingga kecoklatan atau matang.'),
(2, 'cara memasak', 2, 'Masukkan daging ke dalam food processor, tambahkan 2 cube es batu, lalu haluskan daging hingga lumat.'),
(2, 'cara memasak', 3, 'Masukkan bawang putih dan bawang merah goreng, merica, kaldu, garam, baking powder, es batu lagi. Adonan diaduk lagi hingga bercampur rata.'),
(2, 'cara memasak', 4, 'Masukkan tepung tapioka, dan es batu bila perlu. Adonan diaduk lagi hingga merata.'),
(2, 'cara memasak', 5, 'Panaskan air dengan api kecil dan jangan sampai mendidih. Tunggu hingga cukup panas.'),
(2, 'cara memasak', 6, 'Bentuk adonan bakso bulat-bulat sesuai selera menggunakan tangan dan sendok, masukkan bakso ke dalam air yang cukup panas. Tunggu hingga bakso mengapung di atas permukaan air, baru diangkat.'),
(2, 'cara memasak', 7, 'Kuah kaldu tulang: Cuci bersih tulang atau ribs.'),
(2, 'cara memasak', 8, 'Rebus tulang hingga mendidih selama 10 menit, kemudian kecilkan api, biarkan hingga 1 jam atau lebih.'),
(2, 'cara memasak', 9, 'Iris bawang putih dan bawang merah, lalu goreng hingga kecoklatan atau matang. Kemudian blender hingga halus.'),
(2, 'cara memasak', 10, 'Jika rebusan tulang sudah mengeluarkan kaldunya, masukkan bawang putih dan bawang merah yang sudah diblender dan bumbu lainnya ke dalam kuah tersebut. Koreksi rasanya.'),
(2, 'cara memasak', 11, 'Masukkan bakso ke dalam kuah kaldu. Tunggu hingga cukup matang dan kaldu meresap ke dalam bakso.'),
(2, 'cara memasak', 12, 'Masukkan daun bawang dan tambahkan bawang merah goreng.'),
(2, 'cara memasak', 13, 'Sambal bawang: Rebus cabe rawit dan bawang putih hingga empuk. Angkat dan haluskan menggunakan blender atau diulek (tambahkan sedikit garam dan gula). Taruh di mangkok sambal.'),
(2, 'cara memasak', 14, 'Penataan: Masukkan tahu goreng dan mie ke dalam mangkok, lalu tambahkan bakso dan tuangkan kuahnya. Taburkan dengan daun bawang dan bawang goreng, serta sambal bawang.'),
(3, 'cara memasak', 1, 'Panaskan minyak secukupnya lalu tumis bahan yang dihaluskan sampai wangi. Setelah itu masukkan udang yang sudah dilumuri jeruk nipis tadi.'),
(3, 'cara memasak', 2, 'Setelah udang berubah warna masukkan air. Setelah mendidih masukkan kentang.'),
(3, 'cara memasak', 3, 'Setelah kentang lunak masukkan tahu.'),
(3, 'cara memasak', 4, 'Tambahkan juga serai, daun jeruk purut, daun salam, garam, dan penyedap rasa. Aduk-aduk dengan pelan agar tahu tidak hancur.'),
(3, 'cara memasak', 5, 'Setelah bumbu meresap dan harum, masukkan santan bubuk yang telah dicampurkan dengan sedikit air terlebih dahulu. Lanjutkan mengaduk.'),
(3, 'cara memasak', 6, 'Jika kuah dirasa sudah mengental, uji rasa. Bila sudah dirasa pas, angkat dan sajikan langsung dengan nasi panas.'),
(4, 'cara memasak', 1, 'Lumuri ayam menggunakan jeruk nipis, remas-remas dan biarkan selama sekitar 10 menit.'),
(4, 'cara memasak', 2, 'Haluskan bawang putih, kunyit, ketumbar dan lada, lalu tumis hingga harum.'),
(4, 'cara memasak', 3, 'Masukkan ayam dan aduk hingga berubah warna. Tambahkan garam dan santan/air. Masak hingga ayam empuk dan bumbu meresap, matikan api.'),
(4, 'cara memasak', 4, 'Pada panci terpisah, tumis bumbu kuah yang telah dihaluskan bersama daun jeruk hingga harum. Masukkan tomat dan beri garam secukupnya.'),
(4, 'cara memasak', 5, 'Tambahkan santan dan susu ke dalamnya. Masak sampai kuah mendidih sambil ditimba-timba agar santan tidak pecah. Cicipi, jika dirasa sudah pas, masukkan ayam yang telah ditumis tadi ke dalam panci kuah. Masak sekitar 5 menit, matikan api.'),
(4, 'cara memasak', 6, 'Penyajian: Dalam mangkok tata lontong/ketupat yang telah dipotong-potong, telur, tempe, dan tahu putih. Siram dengan kuah glabed panas dan beri potongan ayam. Taburi bawang goreng, beri air jeruk nipis secukupnya serta sambal sesuai selera.'),
(5, 'cara memasak', 1, 'Panaskan 1 sdm minyak goreng lalu tumis tuna menggunakan api sedang sampai kering.'),
(5, 'cara memasak', 2, 'Blender kasar bawang, cabe merah besar, cabe rawit dan sereh.'),
(5, 'cara memasak', 3, 'Panaskan 7 sdm minyak goreng menggunakan api sedang lalu masukkan bahan-bahan yang sudah di blender. Tumis sebentar.'),
(5, 'cara memasak', 4, 'Masukkan air, gula dan garam lalu kecilkan api, masak kurang lebih 20 menit atau sampai air menyusut.'),
(5, 'cara memasak', 5, 'Masukkan tuna, lalu tumis kembali selama 5 menit.'),
(5, 'cara memasak', 6, 'Sambal ini menghasilkan sekitar 300 gr siap santap.'),
(6, 'cara memasak', 1, 'Goreng bawang merah, bawang putih, cabe rawit, dan tomat sebentar sekitar 3 menit. Kemudian blender semua bahan bumbu halus hingga rata (sebaiknya tidak menggunakan air saat memblender, tapi minyak goreng secukupnya).'),
(6, 'cara memasak', 2, 'Panaskan wajan dengan 2-3 sendok makan minyak goreng. Setelah itu, tumis udang sampai matang sekitar 5 menit. Sisihkan.'),
(6, 'cara memasak', 3, 'Di wajan yang sama, tambahkan sesendok minyak goreng lagi, masukkan irisan bawang merah, dan tumis sebentar hingga layu.'),
(6, 'cara memasak', 4, 'Masukkan bumbu halus dan tumis sekitar 5-7 menit. Tambahkan 1/4 cup air. Masukkan bubuk jinten dan kari. Tumis terus sampai harum, sekitar 6 menit.'),
(6, 'cara memasak', 5, 'Masukkan mi yang sudah didinginkan. Aduk terus, lalu tambahkan kecap asin dan manis secukupnya. Tumis terus hingga semua bahan menyatu.'),
(6, 'cara memasak', 6, 'Masukkan tauge. Aduk terus. Tambahkan minyak wijen dan cuka. Aduk terus hingga semua bahan tercampur rata. Koreksi rasanya.'),
(6, 'cara memasak', 7, 'Masukkan udang, daun bawang, dan daun sop. Aduk hingga semuanya tercampur rata.'),
(6, 'cara memasak', 8, 'Mie Aceh Udang siap disajikan dengan irisan tomat, taburan bawang goreng, kerupuk udang, dan kacang tanah goreng.'),
(7, 'cara memasak', 1, 'Haluskan bawang putih, bawang merah, cabai rawit, dan minyak dengan blender kemudian tumis hingga wangi.'),
(7, 'cara memasak', 2, 'Masukkan daun salam dan daun jeruk, tumis hingga wangi dan matang.'),
(7, 'cara memasak', 3, 'Masukkan kecap ikan, seasoning sauce, saus tiram, saus tomat, saus sambal, daun bawang, dan bagian putih, aduk rata.'),
(7, 'cara memasak', 4, 'Tambahkan air, aduk rata lalu masukkan gula dan kaldu bubuk.'),
(7, 'cara memasak', 5, 'Masukkan kerang yang telah direbus.'),
(7, 'cara memasak', 6, 'Panaskan minyak, goreng cumi dan udang selama 30-60 detik, tiriskan.'),
(7, 'cara memasak', 7, 'Masukkan sisa daun bawang, cumi, dan udang yang telah digoreng, (brokoli boleh dicampur atau dipisah untuk hiasan) masak hingga mendidih kemudian matikan api.'),
(7, 'cara memasak', 8, 'Seafood saus padang siap disajikan dengan nasi sebagai pelengkap.'),
(8, 'cara memasak', 1, 'Toping dendeng basah balado. Potong daging setebal 1 cm.'),
(8, 'cara memasak', 2, 'Lumuri dengan bawang putih, merica, dan garam. Biarkan selama 15 menit.'),
(8, 'cara memasak', 3, 'Pindahkan ke wajan, beri air dan masak sampai air habis dan daging empuk, angkat dan tiriskan daging.'),
(8, 'cara memasak', 4, 'Goreng daging dengan minyak panas sebentar saja tidak perlu sampai kering, angkat dan tiriskan.'),
(8, 'cara memasak', 5, 'Tumis cabe dan bawang dengan minyak sisa menggoreng daging hingga layu.'),
(8, 'cara memasak', 6, 'Masukkan daging goreng ke dalam sambal, aduk rata.'),
(8, 'cara memasak', 7, 'Penyajian: Rebus pasta, angkat dan tiriskan kedalam wadah. Sajikan dendeng balado diatas pasta sebagai toping.'),
(9, 'cara memasak', 1, 'Rebus hati ayam 1x mendidih untuk menghilangkan bau amis, tiriskan dan potong sesuai selera kemudian goreng sebentar.'),
(9, 'cara memasak', 2, 'Goreng kentang setengah matang.'),
(9, 'cara memasak', 3, 'Panaskan minyak di atas wajan besar, lalu tumis bumbu halus hingga harum. Tambahkan daun jeruk.'),
(9, 'cara memasak', 4, 'Tuang santan, masak hingga mendidih.'),
(9, 'cara memasak', 5, 'Masukkan hati ayam dan kentang masak hingga air santan habis dan bumbu meresap. Matikan kompor.'),
(10, 'cara memasak', 1, 'Cuci bersih bahan daging dan potong sesuai selera.'),
(10, 'cara memasak', 2, 'Marinasi ayam/daging/hati ayam dengan bumbu tersebut selama 2 jam, taruh di dalam kulkas.'),
(10, 'cara memasak', 3, 'Kemudian rebus dengan 1/2 gelas air dengan api kecil. Atau jika ayam/daging/hati sudah berair maka tidak perlu ditambah air.'),
(10, 'cara memasak', 4, 'Rebus hingga bumbu meresap dan air habis. Dinginkan.'),
(11, 'cara memasak gudeg', 1, 'Haluskan bumbu (disarankan ditumbuk untuk rasa yang lebih mantap).'),
(11, 'cara memasak gudeg', 2, 'Letakkan bumbu rempah di dasar panci/kuali.'),
(11, 'cara memasak gudeg', 3, 'Berikan sedikit garam dan gula merah.'),
(11, 'cara memasak gudeg', 4, 'Lanjutkan masukkan bumbu halus.'),
(11, 'cara memasak gudeg', 5, 'Untuk mendapatkan warna gudeg yang merah gelap bisa ditambahkan 10 sachet black tea.'),
(11, 'cara memasak gudeg', 6, 'Masukkan nangka yang sudah direbus.'),
(11, 'cara memasak gudeg', 7, 'Tuang santan dan tambahkan air sampai nangka terendam.'),
(11, 'cara memasak gudeg', 8, 'Masak dengan api kecil atau dengan slow cooker minimal 4-5 jam.'),
(11, 'cara memasak gudeg', 9, 'Jangan lupa dibolak balik biar tidak gosong.'),
(11, 'cara memasak gudeg', 10, 'Dapat dikoreksi rasanya, sesuai dengan selera.'),
(11, 'sambal krecek - cara memasak', 1, 'Tumis bawang merah dan bawang putih sampai matang dan harum.'),
(11, 'sambal krecek - cara memasak', 2, 'Masukkan cabai halus, lalu tumis lagi hingga benar-benar matang (berubah warna).'),
(11, 'sambal krecek - cara memasak', 3, 'Tuangi 800 ml santan.'),
(11, 'sambal krecek - cara memasak', 4, 'Tunggu sampai mendidih kemudian masukkan kacang tholo, tempe.'),
(11, 'sambal krecek - cara memasak', 5, 'Beri garam, kaldu bubuk serta gula merah.'),
(11, 'sambal krecek - cara memasak', 6, 'Masak sampai bumbu meresap.'),
(11, 'sambal krecek - cara memasak', 7, 'Siap sajikan bersama gudeg.'),
(11, 'opor ayam - cara memasak', 1, 'Tumis bumbu halus hingga harum.'),
(11, 'opor ayam - cara memasak', 2, 'Masukkan bumbu rempah.'),
(11, 'opor ayam - cara memasak', 3, 'Tuangi santan.'),
(11, 'opor ayam - cara memasak', 4, 'Beri garam/kaldu bubuk dan gula merah secukupnya.'),
(11, 'opor ayam - cara memasak', 5, 'Masak sampai ayam empuk dan kuah mengental dengan api kecil.'),
(12, 'cara memasak', 1, 'Campurkan lada, garam dan garlic powder ke dalam tepung terigu. Aduk merata.'),
(12, 'cara memasak', 2, 'Gulirkan ikan ke dalam racikan tepung sampai terlapisi merata.'),
(12, 'cara memasak', 3, 'Panaskan minyak, lalu goreng ikan di atas api sedang sampai matang. Tiriskan dan sisihkan ikan goreng.'),
(12, 'cara memasak', 4, 'Potong tomat cherry menjadi 4 bagian.'),
(12, 'cara memasak', 5, 'Iris tipis bawang merah.'),
(12, 'cara memasak', 6, 'Siapkan mangkuk kecil tahan panas.'),
(12, 'cara memasak', 7, 'Masukkan potongan tomat dan bawang merah, perasan jeruk nipis, irisan daun jeruk, gula, lada dan garam ke dalam mangkuk tahan panas. Sisihkan.'),
(12, 'cara memasak', 8, 'Panaskan minyak sampai panas dan hampir berasap, kemudian segera tuangkan ke dalam mangkuk sambal dabu-dabu. Aduk dan koreksi rasa.'),
(12, 'cara memasak', 9, 'Sajikan ikan goreng di atas piring, tambahkan sambal dabu-dabu diatasnya.'),
(13, 'cara memasak', 1, 'Ayam dibersihkan, dicuci, dan dibelah dua.'),
(13, 'cara memasak', 2, 'Bawang merah, bawang putih, cabai merah, kemiri, jinten, dan ketumbar dihaluskan/diblender.'),
(13, 'cara memasak', 3, 'Panaskan wajan penggorengan dengan menggunakan empat sendok makan minyak goreng. Tumislah bumbu yang sudah dihaluskan sampai harum, dan masukkan serainya.'),
(13, 'cara memasak', 4, 'Masukkan ayamnya diaduk sebentar, kemudian masukkan santannya, yang berikutnya masukkan daun salam, lengkuas, gula jawa dan garam.'),
(13, 'cara memasak', 5, 'Masak sampai santan mendidih, dan tutuplah wajan penggorengan/diungkep sampai santan mulai mengental dan berkurang, serta bumbu-bumbunya meresap. Angkat. Sisa-sisa bumbu jangan dibuang.'),
(13, 'cara memasak', 6, 'Ayam dipanggang di dalam oven atau dibakar diatas grill/barbeque sambil dibolak-balik, sesekali diolesi dengan sisa-sisa bumbu tadi, sampai matangnya merata dan kecoklatan.'),
(13, 'cara memasak', 7, 'Angkat dan sajikan dengan sambal terasi serta lalapan.'),
(14, 'cara memasak', 1, 'Aduk semua bahan menjadi satu hingga rata, kecuali wortel/sosis.'),
(14, 'cara memasak', 2, 'Ambil satu lembar plastik wrap, letakkan diatasnya 1/3 bagian adonan, ratakan pipih.'),
(14, 'cara memasak', 3, 'Letakkan 1 batang wortel atau sosis dibagian tengah. Gulung menjadi seperti lontong. Lakukan pada semua adonan.'),
(14, 'cara memasak', 4, 'Tusuk-tusuk dibeberapa bagian gulungan dengan tusuk gigi.'),
(14, 'cara memasak', 5, 'Kukus selama 30 menit. Angkat, dinginkan.'),
(14, 'cara memasak', 6, 'Goreng. Potong-potong. Sajikan rolade dengan pelengkap saos, wortel, buncis rebus dan French fries.'),
(15, 'cara memasak', 1, 'Potong-potong iga lamb dengan menurut alur tulangnya.'),
(15, 'cara memasak', 2, 'Bumbu dihaluskan, iga lamb dimasukkan dan dicampurkan secara merata kedalam bumbu, dan diinapkan semalam atau kalau terlalu lama setengah hari juga bisa.'),
(15, 'cara memasak', 3, 'Kemudian dipanggang atau dibakar, sesuai selera.'),
(16, 'cara memasak', 1, 'Tumis bawang bombay hingga harum.'),
(16, 'cara memasak', 2, 'Masukkan oregano, daging kambing dan tomat diikuti susu cair masak hingga susu meresap.'),
(16, 'cara memasak', 3, 'Masukkan kocokan telur dan aduk cepat hingga telur tidak pecah, dan diamkan 1 menit hingga telur masak.'),
(16, 'cara memasak', 4, 'Angkat, sajikan dengan nasi hangat.'),
(17, 'cara memasak', 1, 'Panaskan minyak di wajan, campur bahan 1 dan aduk rata.'),
(17, 'cara memasak', 2, 'Cetak dengan tangan bulat-bulat sebesar bola pingpong dan dipipihkan.'),
(17, 'cara memasak', 3, 'Setelah minyak panas, ambil satu adonan, gulingkan ke putih telur (bahan 2).'),
(17, 'cara memasak', 4, 'Goreng sampai kuning kecoklatan.'),
(17, 'cara memasak', 5, 'Sajikan untuk 12-15 buah.'),
(18, 'cara memasak', 1, 'Bumbu halus di tumis sebentar agak harum, dimasukkan serai, daun salam, daun jeruk lalu santannya.'),
(18, 'cara memasak', 2, 'Masukkan tempe kukus, spring green, petai potong kasar, teri, tomat, cabai hijau potongan, daun bawang dan diaduk rata.'),
(18, 'cara memasak', 3, 'Masukkan telur kocok kemudian diaduk rata kembali.'),
(18, 'cara memasak', 4, 'Seluruh bahan dibungkus dengan daun pisang atau alumunium foil sesuai selera. Dapat dijadikan beberapa bungkus, lalu dikukus selama kurang lebih 30 sampai 45 menit.'),
(19, 'cara memasak', 1, 'Rebus curly kale/spring cabbage. Sisihkan.'),
(19, 'cara memasak', 2, 'Saus: goreng cabe + bawang merah, lalu haluskan cabe, terasi, dan bawang merah.'),
(19, 'cara memasak', 3, 'Panaskan sedikit minyak, tumis bumbu halus sampai harum. Tuangi air.'),
(19, 'cara memasak', 4, 'Masukkan asam, gula jawa dan garam. Aduk rata sampai mendidih dan agak kental. Matikan api.'),
(20, 'cara memasak', 1, 'Tumis bawang bombay, bawang putih, hingga harum.'),
(20, 'cara memasak', 2, 'Masukkan udang, tahu dan tambah air sedikit.'),
(20, 'cara memasak', 3, 'Tambahkan kecap, oyster sauce, garam dan merica.'),
(20, 'cara memasak', 4, 'Masukkan daun Mustard Green, aduk hingga rata.'),
(20, 'cara memasak', 5, 'Masak daun Kai Choi setengah matang. Angkat. Sajikan.'),
(21, 'cara memasak', 1, 'Ayam bungkus telor: Campur daging ayam cincang, telor dan bumbu halus, aduk rata.'),
(21, 'cara memasak', 2, 'Ambil selembar dadar, isi dengan 1 sendok makan adonan ayam, lipat seperti amplop/kantong. Lakukan sampai adonan habis.'),
(21, 'cara memasak', 3, 'Kukus selama sekitar 30 menit dan sisihkan.'),
(21, 'cara memasak', 4, 'Kuah sup: Tumis bawang bombay sampai layu.'),
(21, 'cara memasak', 5, 'Masukkan bawang putih dan lada putih, tumis sampai harum.'),
(21, 'cara memasak', 6, 'Tuangi dengan air kaldu ayam, masukkan garam + gula pasir secukupnya.'),
(21, 'cara memasak', 7, 'Rebus sampai mendidih.'),
(21, 'cara memasak', 8, 'Penyajian: Tata ayam bungkus telor, rebusan wortel + jamur putih + kacang polong + irisan daun bawang dan seledri dalam mangkuk/piring. Tuangi dengan kuah panas, sajikan.'),
(22, 'cara memasak', 1, 'Cuci iga kambing, rebus dalam air bersama jahe dan garam hingga berubah warna.'),
(22, 'cara memasak', 2, 'Panaskan minyak, tumis bumbu halus, kayu manis dan cengkeh. Aduk hingga harum dan angkat.'),
(22, 'cara memasak', 3, 'Masukkan ke dalam kaldu rebusan iga. Didihkan dan kecilkan apinya. Tutup panci dan masak hingga bumbu meresap dan daging empuk.'),
(22, 'cara memasak', 4, 'Masukkan wortel dan brokoli, setelah cukup layu.'),
(22, 'cara memasak', 5, 'Masukkan daun bawang dan tomat, dibiarkan cukup layu.'),
(22, 'cara memasak', 6, 'Angkat, sajikan hangat bersama taburan dan pelengkap.'),
(23, 'cara memasak', 1, 'Rebus ayam selama 10 menit, buang rebusan pertama.'),
(23, 'cara memasak', 2, 'Angkat ayam tambahkan 2 liter air dan rebus kembali.'),
(23, 'cara memasak', 3, 'Tumis bumbu halus sampai wangi.'),
(23, 'cara memasak', 4, 'Masukkan bumbu halus ke rebusan ayam.'),
(23, 'cara memasak', 5, 'Masukkan bumbu cemplung lanjut rebus sampai ayam lunak.'),
(23, 'cara memasak', 6, 'Suwir-suwir ayam jika sudah empuk.'),
(23, 'cara memasak', 7, 'Sajikan dengan lontong, telor rebus dan perkedel kentang.'),
(24, 'cara memasak', 1, 'Bersihkan ikan, lumuri dengan perasan jeruk nipis. Sisihkan.'),
(24, 'cara memasak', 2, 'Campur bumbu halus dengan lelehan butter, kecap manis, dan garam ke dalam wadah.'),
(24, 'cara memasak', 3, 'Masukkan ikan ke bumbu, campur hingga merata, kemudian marinate/diamkan sekitar 20 menit (lebih lama lebih baik).'),
(24, 'cara memasak', 4, 'Panaskan oven. Panggang ikan di oven dengan suhu 180 C selama 15 menit, kemudian keluarkan ikan. Olesi dengan sisa bumbu dan panggang kembali selama 15 menit/sampai tingkat kematangan yang diinginkan.'),
(24, 'cara memasak', 5, 'Sajikan dengan sambal bawang dan lalapan.'),
(25, 'cara memasak', 1, 'Rebus dada ayam hingga matang. Suwir-suwir. Sisihkan (air rebusan ayam digunakan untuk kuah kaldu).'),
(25, 'cara memasak', 2, 'Campur tepung plain dan air hingga menjadi adonan kental, beri garam secukupnya. Goreng hingga kecoklatan. Iris kotak-kotak. Sisihkan.'),
(25, 'cara memasak', 3, 'Tumis bawang putih hingga wangi. Masukkan irisan bakso ikan, ayam suwir, lada bubuk dan oyster sauce, aduk rata. Tambahkan kuah kaldu sesuai selera. Tunggu hingga mendidih.'),
(25, 'cara memasak', 4, 'Masukkan wortel, jamur dan tepung goreng. Tutup selama lima menit.'),
(25, 'cara memasak', 5, 'Masukkan pakcoy, daun bawang, dan garam secukupnya. Matikan kompor, koreksi rasa.'),
(25, 'cara memasak', 6, 'Sajikan dengan taburan bawang merah dan cabai goreng.'),
(26, 'cara memasak', 1, 'Rebus ceker ayam selama 10 menit, kemudian buang air rebusan.'),
(26, 'cara memasak', 2, 'Tumis bumbu halus hingga wangi, tambahkan sereh, lengkuas, daun jeruk, dan oyster sauce.'),
(26, 'cara memasak', 3, 'Masukkan ceker, kecap manis, dan garam. Aduk rata.'),
(26, 'cara memasak', 4, 'Tambahkan air. Masak ceker hingga empuk dan bumbu meresap. Koreksi rasa.'),
(26, 'cara memasak', 5, 'Sajikan dengan nasi hangat.'),
(27, 'cara memasak', 1, 'Ceplok telur. Sisihkan.'),
(27, 'cara memasak', 2, 'Tumis bumbu halus hingga wangi, tambahkan lada.'),
(27, 'cara memasak', 3, 'Masukkan telur ceplok dan garam. Aduk rata.'),
(27, 'cara memasak', 4, 'Tambahkan santan. Masak hingga mendidih. Koreksi rasa.'),
(27, 'cara memasak', 5, 'Sajikan dengan nasi hangat.'),
(28, 'cara memasak', 1, 'Telur dadar: Iris tipis bawang merah, bawang putih, cabai, dan daun bawang.'),
(28, 'cara memasak', 2, 'Dalam wadah, pecahkan telur, masukkan irisan bumbu, dan semua bahan. Kocok hingga berbuih.'),
(28, 'cara memasak', 3, 'Panaskan minyak. Goreng telur hingga kuning kecoklatan.'),
(28, 'cara memasak', 4, 'Sambal ijo: Didihkan air. Masukkan cabai, bawang merah, dan bawang putih. Rebus selama 5 menit. Tiriskan.'),
(28, 'cara memasak', 5, 'Haluskan cabai dan bawang yang sudah direbus, tambahkan garam dan lada. Koreksi rasa.'),
(28, 'cara memasak', 6, 'Sajikan telur dadar dan sambal ijo bersama nasi hangat dan lalapan timun dan kale rebus.'),
(29, 'cara memasak', 1, 'Iris pare (jangan terlalu tipis). Beri garam, remas-remas sebentar untuk mengurangi rasa pahit. Cuci.'),
(29, 'cara memasak', 2, 'Tumis bumbu iris hingga wangi. Masukkan pare dan air. Masak hingga pare agak layu dan air menyusut.'),
(29, 'cara memasak', 3, 'Masukkan teri goreng, gula, dan garam. Aduk rata. Koreksi rasa.'),
(29, 'cara memasak', 4, 'Sajikan dengan nasi hangat.'),
(30, 'cara memasak', 1, 'Rebus spaghetti hingga matang, tiriskan.'),
(30, 'cara memasak', 2, 'Tumis bawang putih hingga wangi. Masukkan ayam dan oyster sauce. Tumis hingga ayam matang.'),
(30, 'cara memasak', 3, 'Masukkan spaghetti, kecap manis, lada, daun bawang, dan garam. Aduk rata. Koreksi rasa.'),
(30, 'cara memasak', 4, 'Sajikan selagi hangat, beri taburan bawang merah goreng.'),
(31, 'cara memasak', 1, 'Tumis bumbu halus hingga wangi. Masukkan sereh, lengkuas, daun jeruk. Tumis hingga layu.'),
(31, 'cara memasak', 2, 'Masukkan chicken mince dan ceker. Tambahkan oyster sauce, kecap, garam, dan air. Masak hingga ayam dan ceker matang dan air menyusut.'),
(31, 'cara memasak', 3, 'Masukkan daun bawang.'),
(31, 'cara memasak', 4, 'Koreksi rasa.'),
(32, 'cara memasak', 1, 'Adonan A: Tuang santan ke dalam panci. Masukkan garam dan gula, aduk rata.'),
(32, 'cara memasak', 2, 'Di wadah lain, larutkan tepung terigu dengan santan yang sudah dicampur garam dan gula sekitar 10 sdm.'),
(32, 'cara memasak', 3, 'Saat tepung terigu sudah larut, tuang dan masukkan bersama ke dalam larutan santan dalam panci kemudian didihkan dengan api sedang cenderung kecil, sambil terus diaduk hingga adonan mengental.'),
(32, 'cara memasak', 4, 'Jika sudah mengental, matikan api kompor dan biarkan adonan dingin terlebih dahulu.'),
(32, 'cara memasak', 5, 'Adonan B: Tuang semua bahan B ke dalam panci, aduk rata dan didihkan dengan api kecil.'),
(32, 'cara memasak', 6, 'Aduk adonan hingga mengental dan tidak ada gerindil-gerindil tepung. Matikan api.'),
(32, 'cara memasak', 7, 'Adonan C: Siapkan wadah, masukkan telur dan gula lalu kocok hingga gula pasir larut.'),
(32, 'cara memasak', 8, 'Jika gula pasir sudah larut, masukkan santan kemudian aduk hingga rata.'),
(32, 'cara memasak', 9, 'Masukkan terigu (sebaiknya disaring) sedikit demi sedikit sambil terus diaduk agar terigu tidak menggerindil.'),
(32, 'cara memasak', 10, 'Tuang adonan B ke dalam adonan C lalu aduk sehingga kedua adonan tercampur rata.'),
(32, 'cara memasak', 11, 'Jika adonan B dan C sudah tercampur rata, saring kembali adonan untuk memastikan tidak ada terigu yang menggumpal.'),
(32, 'cara memasak', 12, 'Siapkan cetakan kue (bentuk mencembung), oleskan minyak sayur pada cetakan.'),
(32, 'cara memasak', 13, 'Adonan A masukkan ke dalam plastik piping bag.'),
(32, 'cara memasak', 14, 'Tuang adonan hijau sampai 3/4 cetakan. Lakukan sampai semua cetakan terisi adonan.'),
(32, 'cara memasak', 15, 'Semprotkan adonan A ke dalam masing-masing cetakan kue yang telah diisi adonan hijau.'),
(32, 'cara memasak', 16, 'Siapkan kukusan. Jika kukusan sudah panas, masukkan semua cetakan ke dalam kukusan dan kukus selama 20-25 menit.'),
(32, 'cara memasak', 17, 'Jika kue sudah matang, tunggu hingga kue agak dingin lalu keluarkan dari cetakan.'),
(33, 'cara memasak', 1, 'Bekukan semua buah-buahan ke dalam freezer, kecuali avocado.'),
(33, 'cara memasak', 2, 'Keluarkan semua buah-buahan beku.'),
(33, 'cara memasak', 3, 'Campurkan semua bahan ke dalam bowl besar.'),
(33, 'cara memasak', 4, 'Siram dengan susu terlebih dahulu, serta sedikit syrupnya.'),
(33, 'cara memasak', 5, 'Biarkan meleleh sendiri atau diaduk-aduk agar cepat mencair, atau boleh dipukul-pukul dengan sendok agar bisa menyerupai es crushed.'),
(33, 'cara memasak', 6, 'Siapkan fruit cocktail, (jika kalengan, air cocktailnya jangan diikutkan).'),
(33, 'cara memasak', 7, 'Potong dadu avocado.'),
(33, 'cara memasak', 8, 'Masukkan cocktail fruitnya serta alpukat potongannya, tambahkan syrup atau gula sesuai selera.'),
(33, 'cara memasak', 9, 'Sebelum disajikan, dapat ditambahkan satu sendok teh garam, atau sesuai selera.'),
(34, 'cara memasak', 1, 'Rebus air bersama gula, cengkeh dan kayu manis hingga mendidih.'),
(34, 'cara memasak', 2, 'Jika air sudah mendidih, matikan api, masukkan nanas. Tutup panci selama 10 menit.'),
(34, 'cara memasak', 3, 'Setelah agak dingin, pindahkan ke wadah. Kemudian tambahkan cocktail dan chia seed.'),
(34, 'cara memasak', 4, 'Siap disajikan.'),
(35, 'cara memasak', 1, 'Panggang pisang hingga kecoklatan.'),
(35, 'cara memasak', 2, 'Pipihkan roti tawar menggunakan rolling pan atau tekan-tekan menggunakan sendok makan.'),
(35, 'cara memasak', 3, 'Olesi roti tawar dengan Nutella, beri pisang, keju, kemudian gulung.'),
(35, 'cara memasak', 4, 'Panggang roti menggunakan butter hingga kecoklatan.'),
(35, 'cara memasak', 5, 'Taburi topping.'),
(36, 'cara memasak', 1, 'Tuang dan didihkan air bersama gula merah, asam, kecap dan sejumput garam.'),
(36, 'cara memasak', 2, 'Masak sampai mendidih dan semua bahan tercampur merata. Tunggu sampai air rebusan sedikit berkurang (reduced) dan kuah berwarna lebih gelap.'),
(36, 'cara memasak', 3, 'Diamkan kuah sampai dingin atau suhu ruangan.'),
(36, 'cara memasak', 4, 'Untuk toppingnya, gerus kasar bawang merah dan cabai sesuai selera, lalu sisihkan.'),
(36, 'cara memasak', 5, 'Siapkan mangkuk dan tahu yang sudah dipotong-potong sesuai selera.'),
(36, 'cara memasak', 6, 'Tambahkan gerusan cabai dan bawang diatas tahu.'),
(36, 'cara memasak', 7, 'Siram potongan tahu dengan kuah yang sudah dingin.'),
(37, 'cara memasak', 1, 'Campurkan soft cheese dan gula hingga lembut dengan mixer berkecepatan tinggi.'),
(37, 'cara memasak', 2, 'Tambahkan telur satu per satu, aduk kembali dengan mixer.'),
(37, 'cara memasak', 3, 'Tambahkan heavy cream, aduk rata dengan mixer.'),
(37, 'cara memasak', 4, 'Terakhir masukkan tepung terigu, campur hingga merata.'),
(37, 'cara memasak', 5, 'Alasi loyang dengan baking paper melebihi loyangnya, karena adonan akan mengembang tinggi.'),
(37, 'cara memasak', 6, 'Masukkan ke oven dengan suhu 200 derajat C selama 1 jam. Pada menit ke-50, jika sudah kecoklatan tunggu sekitar 5 menit lalu matikan oven, angkat.'),
(37, 'cara memasak', 7, 'Jika bagian tengah belum settle, tidak mengapa karena nanti saat dingin akan bagus bentuknya.'),
(38, 'cara memasak', 1, 'Panaskan oven api atas 180 dan api bawah 190 derajat Celcius atau 160 derajat Celcius untuk tipe standing oven.'),
(38, 'cara memasak', 2, 'Kocok telur gula sampai kental putih mengembang, turunkan kecepatan, masukkan pisang yang sudah dihaluskan, dan mixer lagi sebentar sampai rata.'),
(38, 'cara memasak', 3, 'Masukkan campuran terigu, kayu manis, soda kue, dan maizena, mixer dengan kecepatan rendah sampai tercampur rata.'),
(38, 'cara memasak', 4, 'Masukkan minyak sayur/lelehan butter, aduk balik dengan spatula.'),
(38, 'cara memasak', 5, 'Setelah benar-benar rata, tuang ke dalam loyang yang sudah dioles mentega dan ditaburi tepung.'),
(38, 'cara memasak', 6, 'Oven selama kurang lebih 45 menit (sampai matang), sesuaikan dengan oven masing-masing. Oven dipanaskan dulu 10-15 menit sebelum loyang masuk.'),
(39, 'cara memasak', 1, 'Peel and fry the banana with butter until golden brown (kupas dan goreng pisang dengan butter sampai kecoklatan).'),
(39, 'cara memasak', 2, 'Cut the banana into 3 cm long.'),
(39, 'cara memasak', 3, 'Cut the cheese into small bar (3 cm long).'),
(39, 'cara memasak', 4, 'Cut the puff pastry sheet into 12 rectangles.'),
(39, 'cara memasak', 5, 'Roll over the pastry sheet forwards and backwards until the small rectangle is about 12 cm x 10 cm.'),
(39, 'cara memasak', 6, 'Put the cheese, banana and one tsp of Nutella in the middle of small puff pastry sheet and wrap it properly.'),
(39, 'cara memasak', 7, 'Brush with beaten egg yolk.'),
(39, 'cara memasak', 8, 'Sprinkle with shredded cheese.'),
(39, 'cara memasak', 9, 'Bake at 200 degrees Celsius for 20-25 minutes (or until golden brown).'),
(40, 'cara memasak', 1, 'Cuci ubi manis sampai bersih kemudian rebus atau kukus sampai matang.'),
(40, 'cara memasak', 2, 'Angkat ubi manis dan buang kulitnya kemudian haluskan di dalam mangkuk.'),
(40, 'cara memasak', 3, 'Masukkan tepung ketan dan aduk merata hingga terbentuk menjadi adonan.'),
(40, 'cara memasak', 4, 'Bentuk adonan menjadi bola-bola kecil dan isi di dalamnya dengan gula merah.'),
(40, 'cara memasak', 5, 'Rebus adonan. Angkat ketika mengambang (matang).'),
(40, 'cara memasak', 6, 'Gulingkan ke kelapa parut.'),
(40, 'cara memasak', 7, 'Sajikan.'),
(41, 'cara memasak', 1, 'Untuk unti: Larutkan gula aren/merah dengan air matang atau santan di dalam panci diatas kompor dengan api sedang. Setelah larut, saring agar larutannya bersih.'),
(41, 'cara memasak', 2, 'Masukkan ke dalam panci yang berisi larutan gula di atas, gula pasir, garam dan daun pandan yang sudah disimpul. Masak hingga mendidih, kemudian masukkan kelapa parut. Dimasak dengan api sedang, sampai larutan gula tercampur dengan parutan kelapa, dan airnya menyusut.'),
(41, 'cara memasak', 3, 'Untuk kulit: Masukkan telur dalam wadah, kocok lepas, tambahkan santannya dan air matang. Aduk rata, masukkan gula pasir dan garamnya, diaduk kembali sampai rata berupa adonan cair.'),
(41, 'cara memasak', 4, 'Bagi menjadi 4 bagian, setiap bagian diberi warna masing-masing dengan pewarna makanan. Siapkan wajan non stick atau teflon, olesi dengan kuas sedikit minyak, dan buat dadar satu persatu untuk warna masing-masing.'),
(41, 'cara memasak', 5, 'Isikan unti kelapa disetiap kulit dadar, satu sendok makan atau satu sendok teh, sesuai dengan besarnya kulit dadar. Dilipat seperti bentuk amplop. Kemudian dihias dengan bentuk bunga atau bintang.'),
(42, 'cara memasak', 1, 'Pilih desicated coconut yang serutannya kasar, jangan pilih yang serutannya halus dan hancur, untuk mendapatkan hasil yang prima.'),
(42, 'cara memasak', 2, 'Desicated coconut dicampur rata dengan santan, dibiarkan terendam beberapa waktu.'),
(42, 'cara memasak', 3, 'Mentega dicairkan/microwave hingga cair, dimasukkan gula dan telur, kemudian dimixer hingga tercampur rata.'),
(42, 'cara memasak', 4, 'Masukkan tepung ketan bergantian dengan desicated coconut + santan pada adonan sebelumnya. Sedikit ditambahkan vanilli dan garam, mixer atau diaduk merata.'),
(42, 'cara memasak', 5, 'Siapkan loyang yang sudah dilapisi kertas roti terlebih dahulu.'),
(42, 'cara memasak', 6, 'Masukkan adonan kedalam loyang, dioven selama 45 menit dengan gas mark-4 atau 180 C.'),
(42, 'cara memasak', 7, 'Jika sudah setengah matang, olesi bagian atas wingko dengan kuning telur.'),
(42, 'cara memasak', 8, 'Panggang kembali hingga matang.'),
(43, 'cara memasak', 1, 'Aduk rata bumbu halus, daging cincang, telur, dan santan kental, sisihkan.'),
(43, 'cara memasak', 2, 'Kocok telur hingga lepas, tambahkan santan, garam, aduk rata. Buat dadar tipis-tipis garis tengah 18 cm.'),
(43, 'cara memasak', 3, 'Ambil selembar dadar, isi dengan adonan daging di tengah, lipat bentuk amplop, gulung. Lakukan hingga adonan habis, kukus hingga matang.'),
(43, 'cara memasak', 4, 'Panaskan sedikit minyak, goreng hingga kuning.'),
(44, 'cara memasak', 1, 'Mix the potatoes, melted butter, egg yolks, milk powder and flour, in the large bowl knead it together until it forms a nice dough, put aside.'),
(44, 'cara memasak', 2, 'Heat 2 tbsp oil, fry the onion and garlic until golden brown, add the minced chicken and cook for 5 minutes then add the grated carrot and chopped spring onion, cook it further until all are soft, add seasoning.'),
(44, 'cara memasak', 3, 'Take 2 tbsp of the dough shape it into a round, then put 1 tbsp of filling, fold and shape it into an oval sausage shape.'),
(44, 'cara memasak', 4, 'Dip it into slightly whisked egg white, then into the breadcrumbs and fry until golden brown.'),
(45, 'cara memasak', 1, 'Mixer kuning telur dengan gula sampai tercampur rata dan mengembang. Tambahkan garam, santan, kentang lembut, dan tepung terigu, diaduk menjadi adonan.'),
(45, 'cara memasak', 2, 'Panaskan loyang kue lumpur di atas kompor, dan loyang diberi olesan mentega/minyak. Masukkan adonan ke dalam loyang setinggi 3/4 tiap lubangnya, dan tutup.'),
(45, 'cara memasak', 3, 'Apabila sudah setengah matang masukkan nangka/raisinnya di atas tiap adonan. Dimasak sekitar 5 menit.'),
(45, 'cara memasak', 4, 'Apabila sudah kelihatan matang, angkat satu persatu, dan masukkan adonan berikutnya sampai habis.'),
(45, 'cara memasak', 5, 'Sajikan, dimakan setelah menunggu dingin sejenak.'),
(46, 'cara memasak', 1, 'Pembuatan bahan dasar/base: Didihkan air di dalam steamer/kukusan.'),
(46, 'cara memasak', 2, 'Campur ketan putih, santan, garam, dan selembar daun pandan dalam panci. Masak dan aduk sampai 3/4 matang (sampai santan meresap dalam ketan dan lembut).'),
(46, 'cara memasak', 3, 'Panaskan loyang yang telah diolesi minyak di dalam kukusan selama 5 menit.'),
(46, 'cara memasak', 4, 'Angkat loyang dan masukkan 3/4 ketan yang sudah setengah matang tadi, dan kukus selama 15 menit.'),
(46, 'cara memasak', 5, 'Pembuatan bahan atas/topping: Campurkan gula, santan, garam, daun pandan ke dalam panci dan masak sampai tercampur rata.'),
(46, 'cara memasak', 6, 'Jika sudah mendidih, sisihkan agar agak dingin.'),
(46, 'cara memasak', 7, 'Kocok telur dan tambahkan tepung terigu, aduk sampai tercampur rata.'),
(46, 'cara memasak', 8, 'Campur adonan telur dan tepung ini ke dalam adonan gula tadi, dan tambahkan pandan extract, kemudian dicampur rata (bisa menggunakan mixer).'),
(46, 'cara memasak', 9, 'Saring adonan tersebut agar tidak ada gumpalan.'),
(46, 'cara memasak', 10, 'Siramkan adonan topping pada adonan ketan yang di dalam kukusan.'),
(46, 'cara memasak', 11, 'Kukus kembali selama 20 menit.'),
(46, 'cara memasak', 12, 'Setelah matang, ambil dari kukusan dan diamkan sementara agar tidak terlalu panas.'),
(46, 'cara memasak', 13, 'Setelah dingin, potong-potong sesuai selera menggunakan pisau yang sudah diberi minyak sedikit.'),
(47, 'cara memasak', 1, 'Letakkan beras ketan di dalam kukusan, tambahkan santan dan garam. Kukus selama 30 menit.'),
(47, 'cara memasak', 2, 'Setelah matang, angkat dan pindahkan ke dalam loyang. Ratakan.'),
(47, 'cara memasak', 3, 'Kocok semua bahan A, tuangkan ke atas nasi ketan.'),
(47, 'cara memasak', 4, 'Kukus hingga masak, kurang lebih 30 menit.'),
(48, 'cara memasak', 1, 'Kukus singkong selama 30 menit atau sampai empuk.'),
(48, 'cara memasak', 2, 'Setelah matang, pindahkan singkong yang masih panas ke dalam baskom, tambahkan vanili.'),
(48, 'cara memasak', 3, 'Tumbuk singkong secara bertahap, sambil masukkan palm sugar, kelapa parut, dan gula pasir.'),
(48, 'cara memasak', 4, 'Cetak tumbukan singkong di loyang, padatkan.'),
(48, 'cara memasak', 5, 'Iris gethuk sesuai selera. Sajikan untuk teman minum teh atau kopi.'),
(49, 'cara memasak', 1, 'Unti kelapa: Rebus air, gula merah, daun pandan, garam, dan vanili. (Saring bila perlu untuk membersihkan ampas gula merah).'),
(49, 'cara memasak', 2, 'Masukkan kelapa parut, masak sambil diaduk sampai agak mengering. Dinginkan dan sisihkan.'),
(49, 'cara memasak', 3, 'Ketan hijau: Campur santan, pasta pandan, beras ketan, daun pandan, dan garam. Masak (sambil sesekali diaduk) dengan api sedang cenderung kecil sampai mengering.'),
(49, 'cara memasak', 4, 'Angkat dan kukus sekitar 30 menit.'),
(49, 'cara memasak', 5, 'Siapkan cetakan (bebas, bisa pakai cetakan talam). Masukkan satu sendok teh unti kelapa, tekan-tekan. Tambahkan ketan di atasnya hingga penuh, keluarkan dari cetakan, sajikan.'),
(50, 'cara memasak', 1, 'Sisir halus gula merah untuk isian klepon.'),
(50, 'cara memasak', 2, 'Siapkan wadah, campur tepung ketan, garam, dan pasta pandan secukupnya. Aduk rata.'),
(50, 'cara memasak', 3, 'Tambahkan air sedikit demi sedikit, uleni adonan tepung sampai kalis kemudian bentuk bulat-bulat.'),
(50, 'cara memasak', 4, 'Pipihkan adonan yang telah dibentuk bulat, beri isian gula merah kemudian bulatkan lagi.'),
(50, 'cara memasak', 5, 'Rebus air hingga mendidih kemudian masukkan bulatan klepon satu persatu, rebus klepon sampai matang (mengapung).'),
(50, 'cara memasak', 6, 'Angkat klepon yang telah matang, tiriskan kemudian gulingkan pada taburan kelapa.'),
(50, 'cara memasak', 7, 'Sajikan klepon untuk camilan bersama teh hangat atau kopi panas.'),
(51, 'cara memasak', 1, 'Tumis bawang bombay hingga layu. Masukkan daging, aduk rata.'),
(51, 'cara memasak', 2, 'Tambahkan garlic powder, ketumbar, jintan, dan garam. Aduk rata kembali hingga daging matang. Sisihkan.'),
(51, 'cara memasak', 3, 'Kocok telur di wadah baskom. Tambahkan daun bawang dan daging. Aduk rata.'),
(51, 'cara memasak', 4, 'Ambil satu lembar kulit spring roll. Beri 3 sendok makan adonan telur, lipat seperti amplop.'),
(51, 'cara memasak', 5, 'Goreng martabak di minyak panas hingga kuning kecoklatan. Tiriskan.'),
(51, 'cara memasak', 6, 'Sajikan dengan acar timun/pickles.'),
(52, 'cara memasak', 1, 'Kupas semua buah-buahan dan ketela pohon/sweet potatoes kemudian diparut (kecuali nanas). Nanas dipotong kecil seperti korek api.'),
(52, 'cara memasak', 2, 'Rebus 250 gr gula merah/jawa dengan air secukupnya sampai mencair.'),
(52, 'cara memasak', 3, 'Haluskan cabai dan terasi, kemudian tambahkan air asam.'),
(52, 'cara memasak', 4, 'Siapkan wadah, masukkan rebusan air gula, bumbu halus dan buah buahan. Aduk hingga tercampur.'),
(52, 'cara memasak', 5, 'Masukkan ke dalam lemari es sekitar satu jam dan sajikan setelah dingin.');

-- ---------------------------------------------------------
-- Data: resep_catatan
-- ---------------------------------------------------------
INSERT INTO `resep_catatan` (`resep_id`, `jenis`, `teks`) VALUES
(8, 'tips', 'Untuk rasa yang lebih enak, bisa juga spaghetti ditumis bersama dengan dendeng balado.'),
(9, 'cara_penyajian', 'Tuang di atas piring saji taburi dengan irisan tipis cabe merah besar (buang biji nya) dan bawang goreng. Masakan ini bisa langsung dimakan dengan nasi putih atau bersamaan dengan opor ayam.'),
(10, 'cara_penyajian', 'Goreng ungkep ayam/daging/hati ayam sebelum dimakan, sajikan dengan sambal ala Indonesia dan nasi panas.'),
(10, 'cara_penyimpanan', 'Untuk di frozen bungkus per porsi di dalam plastik ziplock, setiap saat ingin mengkonsumsi tinggal digoreng.'),
(11, 'tips', 'Jika ingin tekstur gudeg agak basah, boleh hanya memasak 4 jam saja. Jika ingin telur gudeg berwarna coklat gelap, masukkan telur rebus sekalian bersama memasak nangka. Untuk ayam, tahu, dan tempe berwarna coklat gelap, dapat sekalian dimasukkan bersama nangkanya.'),
(19, 'cara_menghidangkan', 'Tata sayuran rebus dalam piring lalu tuangi saus secukupnya. Paling nikmat dimakan bersama kerupuk dan tempe gembus bacem.'),
(20, 'catatan', 'Mustard Green adalah sejenis sawi yang bisa didapatkan di toko Cina, kadang disebut European Kai Choi. Nama lain: Gai Choi, Siu Gai Choi, Xaio Jie Cai, Baby Mustard, Chinese Leaf Mustard, Indian Mustard, Mostaza, dan Mustard Greens.'),
(25, 'catatan', 'Jenis sayuran bisa disesuaikan selera. Protein bisa diganti dengan seafood (udang, cumi, kerang, ikan fillet).'),
(26, 'catatan', 'Ceker ayam/chicken feet/chicken paws tersedia di toko Asia dan beberapa toko daging halal dalam kemasan 1 kg frozen. Cabai rawit merah yang paling mudah ditemukan adalah red bird''s eye chili/red Thai chili.'),
(27, 'catatan', 'Shallot dapat diganti dengan red onion yang lebih mudah didapat dan harganya relatif lebih murah.'),
(29, 'catatan', 'Pare dapat ditemukan dalam bentuk utuh segar maupun kemasan frozen. Ada beberapa jenis pare yang biasa dijual di toko Asia maupun muslim fresh grocery, diantaranya Karela (India) dan Chinese Bitter Melon.'),
(30, 'catatan', 'Untuk mematangkan ayam, tidak perlu ditambah air karena ayam akan mengeluarkan minyak. Ayam dapat diganti dengan seafood atau daging sapi, sesuai selera.'),
(31, 'cara_penyajian', 'Tata mie shanghai di mangkuk. Siram dengan ayam dan kuahnya. Lengkapi dengan pakcoy rebus, ceker, bakso, pangsit, dan taburan daun bawang.'),
(31, 'catatan', 'Chicken mince dapat diganti dengan dada ayam yang direbus kemudian dipotong dadu.'),
(33, 'tips', 'Diusahakan tidak memakai buah nanas agar asamnya tidak merusak rasa. Untuk nanas, jangan dibekukan, biarkan segar, dapat dipotong pada saat terakhir saja sebelum es teler disajikan.'),
(34, 'catatan', 'Simpan di kulkas dan sajikan esok hari untuk rasa yang lebih mantap.'),
(35, 'catatan', 'Sajian untuk 4 porsi.'),
(42, 'catatan', 'Untuk satu resep dengan loyang ukuran 28x24 cm.'),
(46, 'catatan', 'Daun pandan, ketan putih, bisa dibeli di oriental stores.'),
(47, 'catatan', 'Karena tidak punya kukusan yang besar, bisa dipanggang di oven 150C selama 45 menit dengan teknik rendaman panggang (loyang berisi adonan direndam di dalam loyang yang lebih besar berisi air, air rendaman harus dijaga agar tidak habis).'),
(48, 'catatan', 'Cassava/singkong dapat dibeli di toko Asia dalam bentuk singkong segar atau singkong kupas frozen. Gethuk bisa juga digoreng (celupkan dalam adonan tepung plain dengan konsistensi kental, kemudian goreng di minyak panas hingga kecoklatan).');

SET FOREIGN_KEY_CHECKS = 1;